// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type account struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type accountBalance struct {
	Balance int    `json:"balance"`
	Code    string `json:"code"`
	Name    string `json:"name"`
}

type activityRequest struct {
	Billable    bool   `json:"billable"`
	Description string `json:"description"`
	HourlyRate  int    `json:"hourlyRate"`
	Name        string `json:"name"`
	ProductId   int    `json:"productId"`
	ProjectId   int    `json:"projectId"`
}

type activityResult struct {
	ActivityId  int             `json:"activityId"`
	Archived    bool            `json:"archived"`
	Billable    bool            `json:"billable"`
	Description string          `json:"description"`
	HourlyRate  int             `json:"hourlyRate"`
	Name        string          `json:"name"`
	Product     json.RawMessage `json:"product"`
	Project     json.RawMessage `json:"project"`
}

type address struct {
	City               string `json:"city"`
	Country            string `json:"country"`
	PostCode           string `json:"postCode"`
	StreetAddress      string `json:"streetAddress"`
	StreetAddressLine2 string `json:"streetAddressLine2"`
}

type attachment struct {
	Comment                                   string `json:"comment"`
	DownloadUrl                               string `json:"downloadUrl"`
	DownloadUrlWithFikenNormalUserCredentials string `json:"downloadUrlWithFikenNormalUserCredentials"`
	Identifier                                string `json:"identifier"`
	Type                                      string `json:"type"`
}

type bankAccountRequest struct {
	BankAccountNumber string `json:"bankAccountNumber"`
	Bic               string `json:"bic"`
	ForeignService    string `json:"foreignService"`
	Iban              string `json:"iban"`
	Inactive          bool   `json:"inactive"`
	Name              string `json:"name"`
	Type              string `json:"type"`
}

type bankAccountResult struct {
	AccountCode       string `json:"accountCode"`
	BankAccountId     int    `json:"bankAccountId"`
	BankAccountNumber string `json:"bankAccountNumber"`
	Bic               string `json:"bic"`
	ForeignService    string `json:"foreignService"`
	Iban              string `json:"iban"`
	Inactive          bool   `json:"inactive"`
	Name              string `json:"name"`
	ReconciledBalance int    `json:"reconciledBalance"`
	ReconciledDate    string `json:"reconciledDate"`
	Type              string `json:"type"`
}

type bankBalanceResult struct {
	Amount          int    `json:"amount"`
	BankAccountCode string `json:"bankAccountCode"`
	BankAccountId   int    `json:"bankAccountId"`
	Date            string `json:"date"`
	Source          string `json:"source"`
}

type company struct {
	AccountingStartDate string          `json:"accountingStartDate"`
	Address             json.RawMessage `json:"address"`
	CreationDate        string          `json:"creationDate"`
	Email               string          `json:"email"`
	HasApiAccess        bool            `json:"hasApiAccess"`
	Name                string          `json:"name"`
	OrganizationNumber  string          `json:"organizationNumber"`
	PhoneNumber         string          `json:"phoneNumber"`
	Slug                string          `json:"slug"`
	TestCompany         bool            `json:"testCompany"`
	VatRegistrationDate string          `json:"vatRegistrationDate"`
	VatType             string          `json:"vatType"`
}

type contact struct {
	Address                   json.RawMessage `json:"address"`
	BankAccountNumber         string          `json:"bankAccountNumber"`
	ContactId                 int             `json:"contactId"`
	ContactPerson             json.RawMessage `json:"contactPerson"`
	CreatedDate               string          `json:"createdDate"`
	Currency                  string          `json:"currency"`
	Customer                  bool            `json:"customer"`
	CustomerAccountCode       string          `json:"customerAccountCode"`
	CustomerNumber            int             `json:"customerNumber"`
	DaysUntilInvoicingDueDate int             `json:"daysUntilInvoicingDueDate"`
	Discount                  float64         `json:"discount"`
	Documents                 json.RawMessage `json:"documents"`
	Email                     string          `json:"email"`
	Groups                    json.RawMessage `json:"groups"`
	Inactive                  bool            `json:"inactive"`
	Language                  string          `json:"language"`
	LastModifiedDate          string          `json:"lastModifiedDate"`
	MemberNumber              float64         `json:"memberNumber"`
	MemberNumberString        string          `json:"memberNumberString"`
	Name                      string          `json:"name"`
	Notes                     json.RawMessage `json:"notes"`
	OrganizationNumber        string          `json:"organizationNumber"`
	PhoneNumber               string          `json:"phoneNumber"`
	Supplier                  bool            `json:"supplier"`
	SupplierAccountCode       string          `json:"supplierAccountCode"`
	SupplierNumber            int             `json:"supplierNumber"`
}

type contactNote struct {
	Author string `json:"author"`
	Note   string `json:"note"`
}

type contactPerson struct {
	Address         json.RawMessage `json:"address"`
	ContactPersonId int             `json:"contactPersonId"`
	Email           string          `json:"email"`
	Name            string          `json:"name"`
	PhoneNumber     string          `json:"phoneNumber"`
}

type counter struct {
	Value int `json:"value"`
}

type creditNoteLineResult struct {
	Comment       string  `json:"comment"`
	Description   string  `json:"description"`
	Discount      float64 `json:"discount"`
	IncomeAccount string  `json:"incomeAccount"`
	ProductId     int     `json:"productId"`
	Quantity      float64 `json:"quantity"`
	UnitPrice     int     `json:"unitPrice"`
	VatType       string  `json:"vatType"`
}

type creditNoteResult struct {
	Address             json.RawMessage `json:"address"`
	AssociatedInvoiceId int             `json:"associatedInvoiceId"`
	CreditNoteDraftUuid string          `json:"creditNoteDraftUuid"`
	CreditNoteId        int             `json:"creditNoteId"`
	CreditNoteNumber    int             `json:"creditNoteNumber"`
	CreditNotePdf       json.RawMessage `json:"creditNotePdf"`
	CreditNoteText      string          `json:"creditNoteText"`
	Currency            string          `json:"currency"`
	Customer            json.RawMessage `json:"customer"`
	Gross               int             `json:"gross"`
	GrossInNok          int             `json:"grossInNok"`
	IssueDate           string          `json:"issueDate"`
	Kid                 string          `json:"kid"`
	LastModifiedDate    string          `json:"lastModifiedDate"`
	Lines               json.RawMessage `json:"lines"`
	Net                 int             `json:"net"`
	NetInNok            int             `json:"netInNok"`
	OrderReference      string          `json:"orderReference"`
	OurReference        string          `json:"ourReference"`
	Project             json.RawMessage `json:"project"`
	Sale                json.RawMessage `json:"sale"`
	Settled             bool            `json:"settled"`
	Vat                 int             `json:"vat"`
	VatInNok            int             `json:"vatInNok"`
	YourReference       string          `json:"yourReference"`
}

type dispatchResult struct {
	Date         string `json:"date"`
	DispatchType string `json:"dispatchType"`
}

type draftLineRequest struct {
	Gross         int    `json:"gross"`
	IncomeAccount string `json:"incomeAccount"`
	Net           int    `json:"net"`
	ProjectId     int    `json:"projectId"`
	Text          string `json:"text"`
	VatType       string `json:"vatType"`
}

type draftLineResult struct {
	Gross         int             `json:"gross"`
	IncomeAccount string          `json:"incomeAccount"`
	Net           int             `json:"net"`
	Project       json.RawMessage `json:"project"`
	Text          string          `json:"text"`
	VatType       string          `json:"vatType"`
}

type draftRequest struct {
	Cash             bool            `json:"cash"`
	ContactId        int             `json:"contactId"`
	Currency         string          `json:"currency"`
	DueDate          string          `json:"dueDate"`
	InvoiceIssueDate string          `json:"invoiceIssueDate"`
	InvoiceNumber    string          `json:"invoiceNumber"`
	Kid              string          `json:"kid"`
	Lines            json.RawMessage `json:"lines"`
	Paid             bool            `json:"paid"`
	Payments         json.RawMessage `json:"payments"`
	ProjectId        int             `json:"projectId"`
}

type draftResult struct {
	Attachments      json.RawMessage `json:"attachments"`
	Cash             bool            `json:"cash"`
	Contact          json.RawMessage `json:"contact"`
	Currency         string          `json:"currency"`
	DraftId          int             `json:"draftId"`
	DueDate          string          `json:"dueDate"`
	InvoiceIssueDate string          `json:"invoiceIssueDate"`
	InvoiceNumber    string          `json:"invoiceNumber"`
	Kid              string          `json:"kid"`
	Lines            json.RawMessage `json:"lines"`
	Paid             bool            `json:"paid"`
	Payments         json.RawMessage `json:"payments"`
	Project          json.RawMessage `json:"project"`
	Uuid             string          `json:"uuid"`
}

type fullCreditNoteRequest struct {
	CreditNoteText string `json:"creditNoteText"`
	InvoiceId      int    `json:"invoiceId"`
	IssueDate      string `json:"issueDate"`
}

type generalJournalEntryRequest struct {
	Description    string          `json:"description"`
	JournalEntries json.RawMessage `json:"journalEntries"`
	Open           bool            `json:"open"`
}

type inboxResult struct {
	CreatedAt                                 string `json:"createdAt"`
	Description                               string `json:"description"`
	DocumentId                                int    `json:"documentId"`
	DocumentUrl                               string `json:"documentUrl"`
	DocumentUrlWithFikenNormalUserCredentials string `json:"documentUrlWithFikenNormalUserCredentials"`
	Filename                                  string `json:"filename"`
	Name                                      string `json:"name"`
	Status                                    bool   `json:"status"`
}

type invoiceLineRequest struct {
	Comment       string  `json:"comment"`
	Description   string  `json:"description"`
	Discount      float64 `json:"discount"`
	Gross         int     `json:"gross"`
	IncomeAccount string  `json:"incomeAccount"`
	Net           int     `json:"net"`
	ProductId     int     `json:"productId"`
	ProductName   string  `json:"productName"`
	Quantity      float64 `json:"quantity"`
	UnitPrice     int     `json:"unitPrice"`
	Vat           int     `json:"vat"`
	VatInPercent  float64 `json:"vatInPercent"`
	VatType       string  `json:"vatType"`
}

type invoiceLineResult struct {
	Comment       string  `json:"comment"`
	Description   string  `json:"description"`
	Discount      float64 `json:"discount"`
	Gross         int     `json:"gross"`
	GrossInNok    int     `json:"grossInNok"`
	IncomeAccount string  `json:"incomeAccount"`
	Net           int     `json:"net"`
	NetInNok      int     `json:"netInNok"`
	ProductId     int     `json:"productId"`
	ProductName   string  `json:"productName"`
	Quantity      float64 `json:"quantity"`
	UnitPrice     int     `json:"unitPrice"`
	Vat           int     `json:"vat"`
	VatInNok      int     `json:"vatInNok"`
	VatInPercent  float64 `json:"vatInPercent"`
	VatType       string  `json:"vatType"`
}

type invoiceRequest struct {
	BankAccountCode string          `json:"bankAccountCode"`
	Cash            bool            `json:"cash"`
	ContactPersonId int             `json:"contactPersonId"`
	Currency        string          `json:"currency"`
	CustomerId      int             `json:"customerId"`
	DueDate         string          `json:"dueDate"`
	InvoiceText     string          `json:"invoiceText"`
	IssueDate       string          `json:"issueDate"`
	Lines           json.RawMessage `json:"lines"`
	OrderReference  string          `json:"orderReference"`
	OurReference    string          `json:"ourReference"`
	PaymentAccount  string          `json:"paymentAccount"`
	ProjectId       int             `json:"projectId"`
	RoundingType    string          `json:"roundingType"`
	Uuid            string          `json:"uuid"`
	YourReference   string          `json:"yourReference"`
}

type invoiceResult struct {
	Address               json.RawMessage `json:"address"`
	AssociatedCreditNotes json.RawMessage `json:"associatedCreditNotes"`
	Attachments           json.RawMessage `json:"attachments"`
	BankAccountNumber     string          `json:"bankAccountNumber"`
	Cash                  bool            `json:"cash"`
	CreatedDate           string          `json:"createdDate"`
	Currency              string          `json:"currency"`
	Customer              json.RawMessage `json:"customer"`
	Dispatches            json.RawMessage `json:"dispatches"`
	DueDate               string          `json:"dueDate"`
	Gross                 int             `json:"gross"`
	GrossInNok            int             `json:"grossInNok"`
	InvoiceDraftUuid      string          `json:"invoiceDraftUuid"`
	InvoiceId             int             `json:"invoiceId"`
	InvoiceNumber         int             `json:"invoiceNumber"`
	InvoicePdf            json.RawMessage `json:"invoicePdf"`
	InvoiceText           string          `json:"invoiceText"`
	IssueDate             string          `json:"issueDate"`
	Kid                   string          `json:"kid"`
	LastModifiedDate      string          `json:"lastModifiedDate"`
	Lines                 json.RawMessage `json:"lines"`
	Net                   int             `json:"net"`
	NetInNok              int             `json:"netInNok"`
	OrderReference        string          `json:"orderReference"`
	OriginalDueDate       string          `json:"originalDueDate"`
	OurReference          string          `json:"ourReference"`
	Project               json.RawMessage `json:"project"`
	Sale                  json.RawMessage `json:"sale"`
	SentManually          bool            `json:"sentManually"`
	Vat                   int             `json:"vat"`
	VatInNok              int             `json:"vatInNok"`
	YourReference         string          `json:"yourReference"`
}

type invoiceishDraftLine struct {
	Comment               string  `json:"comment"`
	Description           string  `json:"description"`
	Discount              float64 `json:"discount"`
	IncomeAccount         string  `json:"incomeAccount"`
	InvoiceishDraftLineId int     `json:"invoiceishDraftLineId"`
	LastModifiedDate      string  `json:"lastModifiedDate"`
	ProductId             int     `json:"productId"`
	Quantity              float64 `json:"quantity"`
	UnitPrice             int     `json:"unitPrice"`
	VatType               string  `json:"vatType"`
}

type invoiceishDraftRequest struct {
	BankAccountNumber string          `json:"bankAccountNumber"`
	Bic               string          `json:"bic"`
	ContactPersonId   int             `json:"contactPersonId"`
	Currency          string          `json:"currency"`
	CustomerId        int             `json:"customerId"`
	DaysUntilDueDate  int             `json:"daysUntilDueDate"`
	Iban              string          `json:"iban"`
	InvoiceText       string          `json:"invoiceText"`
	IssueDate         string          `json:"issueDate"`
	Lines             json.RawMessage `json:"lines"`
	OrderReference    string          `json:"orderReference"`
	OurReference      string          `json:"ourReference"`
	PaymentAccount    string          `json:"paymentAccount"`
	ProjectId         int             `json:"projectId"`
	RoundingType      string          `json:"roundingType"`
	Type              string          `json:"type"`
	Uuid              string          `json:"uuid"`
	YourReference     string          `json:"yourReference"`
}

type invoiceishDraftResult struct {
	Attachments          json.RawMessage `json:"attachments"`
	BankAccountNumber    string          `json:"bankAccountNumber"`
	Bic                  string          `json:"bic"`
	CreatedFromInvoiceId int             `json:"createdFromInvoiceId"`
	Currency             string          `json:"currency"`
	Customers            json.RawMessage `json:"customers"`
	DaysUntilDueDate     int             `json:"daysUntilDueDate"`
	DraftId              int             `json:"draftId"`
	Gross                int             `json:"gross"`
	Iban                 string          `json:"iban"`
	InvoiceText          string          `json:"invoiceText"`
	IssueDate            string          `json:"issueDate"`
	LastModifiedDate     string          `json:"lastModifiedDate"`
	Lines                json.RawMessage `json:"lines"`
	Net                  int             `json:"net"`
	OrderReference       string          `json:"orderReference"`
	OurReference         string          `json:"ourReference"`
	PaymentAccount       string          `json:"paymentAccount"`
	ProjectId            int             `json:"projectId"`
	RoundingType         string          `json:"roundingType"`
	Type                 string          `json:"type"`
	Uuid                 string          `json:"uuid"`
	YourReference        string          `json:"yourReference"`
}

type journalEntry struct {
	Attachments         json.RawMessage `json:"attachments"`
	CreatedDate         string          `json:"createdDate"`
	Date                string          `json:"date"`
	Description         string          `json:"description"`
	JournalEntryId      int             `json:"journalEntryId"`
	JournalEntryNumber  int             `json:"journalEntryNumber"`
	LastModifiedDate    string          `json:"lastModifiedDate"`
	Lines               json.RawMessage `json:"lines"`
	OffsetTransactionId int             `json:"offsetTransactionId"`
	TransactionId       int             `json:"transactionId"`
}

type journalEntryLine struct {
	Account          string          `json:"account"`
	Amount           int             `json:"amount"`
	CreditAccount    string          `json:"creditAccount"`
	CreditVatCode    int             `json:"creditVatCode"`
	DebitAccount     string          `json:"debitAccount"`
	DebitVatCode     int             `json:"debitVatCode"`
	LastModifiedDate string          `json:"lastModifiedDate"`
	ProjectId        json.RawMessage `json:"projectId"`
	VatCode          string          `json:"vatCode"`
}

type note struct {
	Author string `json:"author"`
	Note   string `json:"note"`
}

type offer struct {
	Accepted        string          `json:"accepted"`
	Address         json.RawMessage `json:"address"`
	Archived        bool            `json:"archived"`
	Comment         string          `json:"comment"`
	ContactId       int             `json:"contactId"`
	ContactPersonId int             `json:"contactPersonId"`
	Currency        string          `json:"currency"`
	Date            string          `json:"date"`
	Discount        float64         `json:"discount"`
	Dispatches      json.RawMessage `json:"dispatches"`
	Gross           int             `json:"gross"`
	Lines           json.RawMessage `json:"lines"`
	Net             int             `json:"net"`
	OfferDraftUuid  string          `json:"offerDraftUuid"`
	OfferId         int             `json:"offerId"`
	OfferNumber     int             `json:"offerNumber"`
	OrderReference  string          `json:"orderReference"`
	OurReference    string          `json:"ourReference"`
	ProjectId       int             `json:"projectId"`
	Vat             int             `json:"vat"`
	YourReference   string          `json:"yourReference"`
}

type orderConfirmation struct {
	Address               json.RawMessage `json:"address"`
	Archived              bool            `json:"archived"`
	Comment               string          `json:"comment"`
	ConfirmationDraftUuid string          `json:"confirmationDraftUuid"`
	ConfirmationId        int             `json:"confirmationId"`
	ConfirmationNumber    int             `json:"confirmationNumber"`
	ContactId             int             `json:"contactId"`
	ContactPersonId       int             `json:"contactPersonId"`
	CreatedInvoice        int             `json:"createdInvoice"`
	Currency              string          `json:"currency"`
	Date                  string          `json:"date"`
	Discount              float64         `json:"discount"`
	Gross                 int             `json:"gross"`
	InternalComment       string          `json:"internalComment"`
	Lines                 json.RawMessage `json:"lines"`
	Net                   int             `json:"net"`
	OrderReference        string          `json:"orderReference"`
	OurReference          string          `json:"ourReference"`
	ProjectId             int             `json:"projectId"`
	Vat                   int             `json:"vat"`
	YourReference         string          `json:"yourReference"`
}

type orderLine struct {
	Account            string `json:"account"`
	Description        string `json:"description"`
	NetPrice           int    `json:"netPrice"`
	NetPriceInCurrency int    `json:"netPriceInCurrency"`
	ProjectId          int    `json:"projectId"`
	Vat                int    `json:"vat"`
	VatInCurrency      int    `json:"vatInCurrency"`
	VatType            string `json:"vatType"`
}

type partialCreditNoteRequest struct {
	ContactId       int             `json:"contactId"`
	ContactPersonId int             `json:"contactPersonId"`
	CreditNoteText  string          `json:"creditNoteText"`
	Currency        string          `json:"currency"`
	InvoiceId       int             `json:"invoiceId"`
	IssueDate       string          `json:"issueDate"`
	Lines           json.RawMessage `json:"lines"`
	OrderReference  string          `json:"orderReference"`
	OurReference    string          `json:"ourReference"`
	Project         int             `json:"project"`
	RoundingType    string          `json:"roundingType"`
	YourReference   string          `json:"yourReference"`
}

type payment struct {
	Account     string `json:"account"`
	Amount      int    `json:"amount"`
	AmountInNok int    `json:"amountInNok"`
	Currency    string `json:"currency"`
	Date        string `json:"date"`
	Fee         int    `json:"fee"`
	PaymentId   int    `json:"paymentId"`
}

type product struct {
	Active           bool    `json:"active"`
	CreatedDate      string  `json:"createdDate"`
	IncomeAccount    string  `json:"incomeAccount"`
	LastModifiedDate string  `json:"lastModifiedDate"`
	Name             string  `json:"name"`
	Note             string  `json:"note"`
	ProductId        int     `json:"productId"`
	ProductNumber    string  `json:"productNumber"`
	Stock            float64 `json:"stock"`
	UnitPrice        int     `json:"unitPrice"`
	VatType          string  `json:"vatType"`
}

type productSalesLineInfo struct {
	Count       int `json:"count"`
	GrossAmount int `json:"grossAmount"`
	NetAmount   int `json:"netAmount"`
	Sales       int `json:"sales"`
	VatAmount   int `json:"vatAmount"`
}

type productSalesReportRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type productSalesReportResult struct {
	Credited json.RawMessage `json:"credited"`
	Product  json.RawMessage `json:"product"`
	Sold     json.RawMessage `json:"sold"`
	Sum      json.RawMessage `json:"sum"`
}

type projectRequest struct {
	Completed   bool   `json:"completed"`
	ContactId   int    `json:"contactId"`
	Description string `json:"description"`
	EndDate     string `json:"endDate"`
	Name        string `json:"name"`
	Number      string `json:"number"`
	StartDate   string `json:"startDate"`
}

type projectResult struct {
	Completed   bool            `json:"completed"`
	Contact     json.RawMessage `json:"contact"`
	Description string          `json:"description"`
	EndDate     string          `json:"endDate"`
	Name        string          `json:"name"`
	Number      string          `json:"number"`
	ProjectId   int             `json:"projectId"`
	StartDate   string          `json:"startDate"`
}

type purchaseRequest struct {
	Currency           string          `json:"currency"`
	Date               string          `json:"date"`
	DueDate            string          `json:"dueDate"`
	Identifier         string          `json:"identifier"`
	Kid                string          `json:"kid"`
	Kind               string          `json:"kind"`
	Lines              json.RawMessage `json:"lines"`
	PaymentAccount     string          `json:"paymentAccount"`
	PaymentAmountInNok int             `json:"paymentAmountInNok"`
	PaymentDate        string          `json:"paymentDate"`
	ProjectId          int             `json:"projectId"`
	SupplierId         int             `json:"supplierId"`
	TransactionId      int             `json:"transactionId"`
}

type purchaseResult struct {
	Currency            string          `json:"currency"`
	Date                string          `json:"date"`
	Deleted             bool            `json:"deleted"`
	DueDate             string          `json:"dueDate"`
	Identifier          string          `json:"identifier"`
	Kid                 string          `json:"kid"`
	Kind                string          `json:"kind"`
	Lines               json.RawMessage `json:"lines"`
	Paid                bool            `json:"paid"`
	PaymentAccount      string          `json:"paymentAccount"`
	PaymentDate         string          `json:"paymentDate"`
	Payments            json.RawMessage `json:"payments"`
	Project             json.RawMessage `json:"project"`
	PurchaseAttachments json.RawMessage `json:"purchaseAttachments"`
	PurchaseId          int             `json:"purchaseId"`
	Settled             bool            `json:"settled"`
	SettledDate         string          `json:"settledDate"`
	Supplier            json.RawMessage `json:"supplier"`
	TransactionId       int             `json:"transactionId"`
}

type saleRequest struct {
	Currency            string          `json:"currency"`
	CustomerId          int             `json:"customerId"`
	Date                string          `json:"date"`
	DueDate             string          `json:"dueDate"`
	Kid                 string          `json:"kid"`
	Kind                string          `json:"kind"`
	Lines               json.RawMessage `json:"lines"`
	PaymentAccount      string          `json:"paymentAccount"`
	PaymentDate         string          `json:"paymentDate"`
	PaymentFee          int             `json:"paymentFee"`
	ProjectId           int             `json:"projectId"`
	SaleNumber          string          `json:"saleNumber"`
	TotalPaid           int             `json:"totalPaid"`
	TotalPaidInCurrency int             `json:"totalPaidInCurrency"`
}

type saleResult struct {
	Currency                     string          `json:"currency"`
	Customer                     json.RawMessage `json:"customer"`
	Date                         string          `json:"date"`
	Deleted                      bool            `json:"deleted"`
	DueDate                      string          `json:"dueDate"`
	Kid                          string          `json:"kid"`
	Kind                         string          `json:"kind"`
	LastModifiedDate             string          `json:"lastModifiedDate"`
	Lines                        json.RawMessage `json:"lines"`
	NetAmount                    int             `json:"netAmount"`
	Notes                        json.RawMessage `json:"notes"`
	OutstandingBalance           int             `json:"outstandingBalance"`
	OutstandingBalanceInCurrency int             `json:"outstandingBalanceInCurrency"`
	PaymentAccount               string          `json:"paymentAccount"`
	PaymentDate                  string          `json:"paymentDate"`
	Project                      json.RawMessage `json:"project"`
	SaleAttachments              json.RawMessage `json:"saleAttachments"`
	SaleId                       int             `json:"saleId"`
	SaleNumber                   string          `json:"saleNumber"`
	SalePayments                 json.RawMessage `json:"salePayments"`
	Settled                      bool            `json:"settled"`
	SettledDate                  string          `json:"settledDate"`
	TotalPaid                    int             `json:"totalPaid"`
	TotalPaidInCurrency          int             `json:"totalPaidInCurrency"`
	TransactionId                int             `json:"transactionId"`
	VatAmount                    int             `json:"vatAmount"`
	WriteOff                     bool            `json:"writeOff"`
}

type sendCreditNoteRequest struct {
	CreditNoteId               int             `json:"creditNoteId"`
	EmailSendOption            string          `json:"emailSendOption"`
	IncludeDocumentAttachments bool            `json:"includeDocumentAttachments"`
	MergeInvoiceAndAttachments bool            `json:"mergeInvoiceAndAttachments"`
	Message                    string          `json:"message"`
	Method                     json.RawMessage `json:"method"`
	MobileNumber               string          `json:"mobileNumber"`
	OrganizationNumber         string          `json:"organizationNumber"`
	RecipientEmail             string          `json:"recipientEmail"`
	RecipientName              string          `json:"recipientName"`
}

type sendInvoiceRequest struct {
	EmailSendOption            string          `json:"emailSendOption"`
	IncludeDocumentAttachments bool            `json:"includeDocumentAttachments"`
	InvoiceId                  int             `json:"invoiceId"`
	MergeInvoiceAndAttachments bool            `json:"mergeInvoiceAndAttachments"`
	Message                    string          `json:"message"`
	Method                     json.RawMessage `json:"method"`
	MobileNumber               string          `json:"mobileNumber"`
	OrganizationNumber         string          `json:"organizationNumber"`
	RecipientEmail             string          `json:"recipientEmail"`
	RecipientName              string          `json:"recipientName"`
}

type sendInvoiceishRequest struct {
	EmailSendOption            string          `json:"emailSendOption"`
	IncludeDocumentAttachments bool            `json:"includeDocumentAttachments"`
	MergeInvoiceAndAttachments bool            `json:"mergeInvoiceAndAttachments"`
	Message                    string          `json:"message"`
	Method                     json.RawMessage `json:"method"`
	MobileNumber               string          `json:"mobileNumber"`
	OrganizationNumber         string          `json:"organizationNumber"`
	RecipientEmail             string          `json:"recipientEmail"`
	RecipientName              string          `json:"recipientName"`
}

type sendOfferRequest struct {
	EmailSendOption            string          `json:"emailSendOption"`
	IncludeDocumentAttachments bool            `json:"includeDocumentAttachments"`
	MergeInvoiceAndAttachments bool            `json:"mergeInvoiceAndAttachments"`
	Message                    string          `json:"message"`
	Method                     json.RawMessage `json:"method"`
	MobileNumber               string          `json:"mobileNumber"`
	OfferId                    int             `json:"offerId"`
	OrganizationNumber         string          `json:"organizationNumber"`
	RecipientEmail             string          `json:"recipientEmail"`
	RecipientName              string          `json:"recipientName"`
}

type timeEntryInvoiceDraftRequest struct {
	BankAccountNumber            string          `json:"bankAccountNumber"`
	Currency                     string          `json:"currency"`
	CustomerId                   int             `json:"customerId"`
	DaysUntilDueDate             int             `json:"daysUntilDueDate"`
	GroupBy                      string          `json:"groupBy"`
	IncludeTimeEntryDescriptions bool            `json:"includeTimeEntryDescriptions"`
	InvoiceText                  string          `json:"invoiceText"`
	IssueDate                    string          `json:"issueDate"`
	OrderReference               string          `json:"orderReference"`
	OurReference                 string          `json:"ourReference"`
	ProjectId                    int             `json:"projectId"`
	TimeEntryIds                 json.RawMessage `json:"timeEntryIds"`
	YourReference                string          `json:"yourReference"`
}

type timeEntryRequest struct {
	ActivityId   int     `json:"activityId"`
	Date         string  `json:"date"`
	Description  string  `json:"description"`
	Hours        float64 `json:"hours"`
	InternalNote string  `json:"internalNote"`
	ProjectId    int     `json:"projectId"`
	StartTime    string  `json:"startTime"`
	TimeUserId   int     `json:"timeUserId"`
}

type timeEntryResult struct {
	Activity         json.RawMessage `json:"activity"`
	CreatedDate      string          `json:"createdDate"`
	Date             string          `json:"date"`
	Description      string          `json:"description"`
	EndTime          string          `json:"endTime"`
	Hours            float64         `json:"hours"`
	InternalNote     string          `json:"internalNote"`
	InvoiceId        int             `json:"invoiceId"`
	Invoiced         bool            `json:"invoiced"`
	LastModifiedDate string          `json:"lastModifiedDate"`
	Locked           bool            `json:"locked"`
	Project          json.RawMessage `json:"project"`
	StartTime        string          `json:"startTime"`
	TimeEntryId      int             `json:"timeEntryId"`
	TimeUser         json.RawMessage `json:"timeUser"`
}

type timeUserRequest struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type timeUserResult struct {
	CreatedDate      string `json:"createdDate"`
	Email            string `json:"email"`
	LastModifiedDate string `json:"lastModifiedDate"`
	Name             string `json:"name"`
	TimeUserId       int    `json:"timeUserId"`
}

type transaction struct {
	CreatedDate      string          `json:"createdDate"`
	Deleted          bool            `json:"deleted"`
	Description      string          `json:"description"`
	Entries          json.RawMessage `json:"entries"`
	LastModifiedDate string          `json:"lastModifiedDate"`
	TransactionId    int             `json:"transactionId"`
	Type             string          `json:"type"`
}

type updateActivityRequest struct {
	Billable    bool   `json:"billable"`
	Description string `json:"description"`
	HourlyRate  int    `json:"hourlyRate"`
	Name        string `json:"name"`
	ProductId   int    `json:"productId"`
	ProjectId   int    `json:"projectId"`
}

type updateInvoiceRequest struct {
	NewDueDate   string `json:"newDueDate"`
	SentManually bool   `json:"sentManually"`
}

type updateProjectRequest struct {
	Completed   bool   `json:"completed"`
	ContactId   int    `json:"contactId"`
	Description string `json:"description"`
	EndDate     string `json:"endDate"`
	Name        string `json:"name"`
	StartDate   string `json:"startDate"`
}

type updateTimeEntryRequest struct {
	ActivityId   int     `json:"activityId"`
	Date         string  `json:"date"`
	Description  string  `json:"description"`
	Hours        float64 `json:"hours"`
	InternalNote string  `json:"internalNote"`
	ProjectId    int     `json:"projectId"`
	StartTime    string  `json:"startTime"`
}

type userinfo struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type writeOffRequest struct {
	Comment string `json:"comment"`
	Date    string `json:"date"`
	Type    string `json:"type"`
}
