// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"fiken-cli/internal/cli"
	"fiken-cli/internal/client"
	"fiken-cli/internal/cliutil"
	"fiken-cli/internal/config"
	"fiken-cli/internal/mcp/cobratree"
	"fiken-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

const (
	mcpToolResultMaxBytes = 60000
	mcpToolResultMaxItems = 50
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='items'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName         string
	WireName           string
	Location           string
	BodyPath           []string
	Format             string
	RequestContentType string
	Default            string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", v)
	}
}
func mcpMultipartFieldValue(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	if data, err := json.Marshal(v); err == nil {
		return string(data)
	}
	return fmt.Sprintf("%v", v)
}
func setNestedBodyArg(body map[string]any, path []string, value any) {
	if len(path) == 0 {
		return
	}
	if len(path) == 1 {
		body[path[0]] = value
		return
	}
	current := body
	for _, key := range path[:len(path)-1] {
		next, ok := current[key].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	current[path[len(path)-1]] = value
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient(ctx)
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		multipartFields := make(map[string]string)
		multipartFileFields := make(map[string]string)
		multipart := false
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			if strings.EqualFold(binding.RequestContentType, "multipart/form-data") {
				multipart = true
			}
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				if len(binding.BodyPath) > 0 {
					setNestedBodyArg(bodyArgs, binding.BodyPath, v)
				} else {
					bodyArgs[binding.WireName] = v
				}
				if multipart {
					if strings.EqualFold(binding.Format, "binary") {
						multipartFileFields[binding.WireName] = fmt.Sprintf("%v", v)
					} else {
						multipartFields[binding.WireName] = mcpMultipartFieldValue(v)
					}
				}
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
				if multipart {
					multipartFields[k] = mcpMultipartFieldValue(v)
				}
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PostMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PostMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
				break
			}
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PutMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PutMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
				break
			}
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PatchMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PatchMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
				break
			}
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export FIKEN_API_TOKEN=<your-key>" +
					"\n      Get a key at: https://fiken.no/" +
					"\n      Run 'fiken-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export FIKEN_API_TOKEN=<your-key>" +
					"\n      Get a key at: https://fiken.no/" +
					"\n      Run 'fiken-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export FIKEN_API_TOKEN=<your-key>" +
					"\n      Get a key at: https://fiken.no/" +
					"\n      Run 'fiken-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	trimmed := strings.TrimSpace(string(data))
	if strings.EqualFold(method, "GET") && len(trimmed) > 0 && trimmed[0] == '[' {
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			return mcplib.NewToolResultText(string(mcpBoundedListEnvelope("items", items, len(data))))
		}
	}
	if len(data) <= mcpToolResultMaxBytes {
		return mcplib.NewToolResultText(string(data))
	}
	if strings.EqualFold(method, "GET") {
		if out, ok := mcpBoundedSingleArrayObject(data); ok {
			return mcplib.NewToolResultText(string(out))
		}
	}
	return mcplib.NewToolResultText(string(mcpOversizedPreviewEnvelope(data)))
}

func mcpBoundedSingleArrayObject(data json.RawMessage) ([]byte, bool) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	arrayField := ""
	var items []json.RawMessage
	for key, raw := range obj {
		trimmed := strings.TrimSpace(string(raw))
		if len(trimmed) == 0 || trimmed[0] != '[' {
			continue
		}
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) != nil {
			continue
		}
		if arrayField != "" {
			return nil, false
		}
		arrayField = key
		items = candidate
	}
	if arrayField == "" {
		return nil, false
	}
	build := func(subset []json.RawMessage) any {
		out := make(map[string]any, len(obj)+6)
		for key, raw := range obj {
			if key == arrayField {
				out[key] = subset
				continue
			}
			out[key] = raw
		}
		if len(subset) < len(items) {
			out["_pp_truncated"] = true
			out["_pp_total_count"] = len(items)
			out["_pp_returned_count"] = len(subset)
			out["_pp_original_bytes"] = len(data)
			out["_pp_max_bytes"] = mcpToolResultMaxBytes
			out["_pp_note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	out := mcpFitJSONItems(items, build)
	if len(out) > mcpToolResultMaxBytes {
		return nil, false
	}
	return out, true
}

func mcpBoundedListEnvelope(field string, items []json.RawMessage, originalBytes int) []byte {
	build := func(subset []json.RawMessage) any {
		out := map[string]any{
			"count": len(items),
			field:   subset,
		}
		if len(subset) < len(items) {
			out["truncated"] = true
			out["returned_count"] = len(subset)
			out["original_bytes"] = originalBytes
			out["max_bytes"] = mcpToolResultMaxBytes
			out["note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	return mcpFitJSONItems(items, build)
}

func mcpFitJSONItems(items []json.RawMessage, build func([]json.RawMessage) any) []byte {
	limit := len(items)
	if limit > mcpToolResultMaxItems {
		limit = mcpToolResultMaxItems
	}
	for n := limit; n >= 0; n-- {
		out, err := json.Marshal(build(items[:n]))
		if err != nil {
			continue
		}
		if len(out) <= mcpToolResultMaxBytes || n == 0 {
			return out
		}
	}
	out, _ := json.Marshal(build(items[:0]))
	return out
}

func mcpOversizedPreviewEnvelope(data json.RawMessage) []byte {
	previewBytes := data
	if len(previewBytes) > 4000 {
		previewBytes = previewBytes[:4000]
	}
	out, _ := json.Marshal(map[string]any{
		"truncated":      true,
		"original_bytes": len(data),
		"max_bytes":      mcpToolResultMaxBytes,
		"preview":        string(previewBytes),
		"note":           "Typed MCP endpoint response exceeded the tool result budget and was not a recognized list envelope. Narrow the request with filters, search/sql, or a command-mirror tool with --agent/--compact/--select.",
	})
	return out
}

func newMCPClient(ctx context.Context) (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "fiken-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	// Streamable-HTTP transport: the caller's per-request Fiken OAuth Bearer
	// token (fiken_http_auth.go) overrides the server's locally-stored token,
	// so the server acts on behalf of whoever connected. AccessToken wins over
	// the env/config bearer in the client. Empty for stdio (uses local config).
	if tok := fikenTokenFromContext(ctx); tok != "" {
		cfg.AccessToken = tok
	}
	// PATCH(test-company-write-guard): MCP is an agent surface, so it is wired
	// to test mode unconditionally. See internal/cli/write_guard_setup.go.
	cli.ConfigureWriteGuardForMCP()
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "fiken-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	return toolResultJSON(results)
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	return toolResultJSON(results)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "fiken",
		"description": "The agent-native Fiken CLI: full read coverage with offline search and a local SQLite mirror, plus the gated, audited",
		"archetype":   "payments",
		"tool_count":  153,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion fiken-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "FIKEN_API_TOKEN",
					"kind":        "per_call",
					"required":    false,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
				{
					"name":        "FIKEN_CLIENT_ID",
					"kind":        "auth_flow_input",
					"required":    false,
					"sensitive":   false,
					"description": "OAuth2 client ID, used only by 'auth login' when acting on behalf of other companies. Not needed if you use a personal API token.",
				},
				{
					"name":        "FIKEN_CLIENT_SECRET",
					"kind":        "auth_flow_input",
					"required":    false,
					"sensitive":   true,
					"description": "Set during initial auth setup.",
				},
			},
			"key_url": "https://fiken.no/",
		},
		"resources": []map[string]any{
			{
				"name":        "account-balances",
				"description": "Manage account balances",
				"endpoints":   []string{"get", "get-companies"},
				"searchable":  true,
			},
			{
				"name":        "accounts",
				"description": "Manage accounts",
				"endpoints":   []string{"get", "get-companies"},
				"searchable":  true,
			},
			{
				"name":        "activities",
				"description": "Manage activities",
				"endpoints":   []string{"create-activity", "delete-activity", "get", "get-activity", "update-activity"},
				"searchable":  true,
			},
			{
				"name":        "bank-accounts",
				"description": "Manage bank accounts",
				"endpoints":   []string{"create", "get", "get-companies"},
				"searchable":  true,
			},
			{
				"name":        "bank-balances",
				"description": "Manage bank balances",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "companies",
				"description": "Manage companies",
				"endpoints":   []string{"get", "get-company"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "contacts",
				"description": "Manage contacts",
				"endpoints":   []string{"create", "delete", "get", "get-companies", "update"},
				"searchable":  true,
			},
			{
				"name":        "credit-notes",
				"description": "Manage credit notes",
				"endpoints":   []string{"add-attachment-to-draft", "create-counter", "create-draft", "create-from-draft", "create-full", "create-partial", "delete-draft", "get", "get-companies", "get-counter", "get-draft", "get-draft-attachments", "get-drafts", "send", "update-draft"},
				"searchable":  true,
			},
			{
				"name":        "general-journal-entries",
				"description": "Manage general journal entries",
				"endpoints":   []string{"create-general-journal-entry"},
				"searchable":  true,
			},
			{
				"name":        "groups",
				"description": "Manage groups",
				"endpoints":   []string{"get"},
				"searchable":  true,
			},
			{
				"name":        "inbox",
				"description": "Manage inbox",
				"endpoints":   []string{"create-document", "delete-document", "get", "get-document"},
				"searchable":  true,
			},
			{
				"name":        "invoices",
				"description": "Manage invoices",
				"endpoints":   []string{"add-attachment-to-draft", "create", "create-counter", "create-draft", "create-from-draft", "delete-draft", "get", "get-companies", "get-counter", "get-draft", "get-draft-attachments", "get-drafts", "send", "update", "update-draft"},
				"searchable":  true,
			},
			{
				"name":        "journal-entries",
				"description": "Manage journal entries",
				"endpoints":   []string{"get", "get-journal-entry"},
				"searchable":  true,
			},
			{
				"name":        "offers",
				"description": "Manage offers",
				"endpoints":   []string{"add-attachment-to-draft", "create-counter", "create-draft", "create-from-draft", "delete-draft", "get", "get-companies", "get-counter", "get-draft", "get-draft-attachments", "get-drafts", "send", "update-draft"},
				"searchable":  true,
			},
			{
				"name":        "order-confirmations",
				"description": "Manage order confirmations",
				"endpoints":   []string{"add-attachment-to-draft", "create-counter", "create-draft", "create-from-draft", "delete-draft", "get", "get-companies", "get-counter", "get-draft", "get-draft-attachments", "get-drafts", "update-draft"},
				"searchable":  true,
			},
			{
				"name":        "products",
				"description": "Manage products",
				"endpoints":   []string{"create", "create-sales-report", "delete", "get", "get-companies", "update"},
				"searchable":  true,
			},
			{
				"name":        "projects",
				"description": "Manage projects",
				"endpoints":   []string{"create", "delete", "get", "get-companies", "update"},
				"searchable":  true,
			},
			{
				"name":        "purchases",
				"description": "Manage purchases",
				"endpoints":   []string{"add-attachment-to-draft", "create", "create-draft", "create-from-draft", "delete-draft", "get", "get-companies", "get-draft", "get-draft-attachments", "get-drafts", "update-draft"},
				"searchable":  true,
			},
			{
				"name":        "sales",
				"description": "Manage sales",
				"endpoints":   []string{"add-attachment-to-draft", "create", "create-draft", "create-from-draft", "delete-draft", "get", "get-companies", "get-draft", "get-draft-attachments", "get-drafts", "update-draft"},
				"searchable":  true,
			},
			{
				"name":        "time-entries",
				"description": "Manage time entries",
				"endpoints":   []string{"create-invoice-draft-from", "create-time-entry", "delete-time-entry", "get", "get-time-entry", "update-time-entry"},
				"searchable":  true,
			},
			{
				"name":        "time-users",
				"description": "Manage time users",
				"endpoints":   []string{"get", "get-companies"},
				"searchable":  true,
			},
			{
				"name":        "transactions",
				"description": "Manage transactions",
				"endpoints":   []string{"get", "get-companies"},
				"searchable":  true,
			},
			{
				"name":        "user",
				"description": "Manage user",
				"endpoints":   []string{"get"},
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass page parameter for subsequent pages.",
			"Control page size with the pageSize parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Unverified-against-bank detector", "command": "bank-unverified", "description": "Lists postings on your bank accounts that aren't yet matched to the bank statement, and shows the exact ledger-vs-reconciled gap per account.", "rationale": "Requires joining account balances, each bank account's reconciledBalance/reconciledDate, and transactions in the local store — data that only exists together offline; Fiken exposes no such query.", "via": "mcp-command-mirror"},
			{"name": "Client-side posting validation", "command": "validate", "description": "Dry-runs a proposed posting before it touches the books: balanced debit/credit in øre, account exists, MVA code plausible for the account, period open, date sane.", "rationale": "Fiken has no dry-run; the only way to catch an unbalanced or mis-coded entry today is to post it and see it fail. We check locally against the synced chart of accounts and the embedded VAT-code table.", "via": "mcp-command-mirror"},
			{"name": "Idempotent audited commit", "command": "commit", "description": "Posts a validated purchase or journal entry through a guarded path: deduped against the idempotency map, date-aligned to the expected bank-line date, X-Request-ID stamped, and recorded in an append-only audit log in the same call.", "rationale": "Double-posting real books is unrecoverable; no Fiken tool offers idempotency or an audit trail. Our local core DB makes both structural.", "via": "mcp-command-mirror"},
			{"name": "Imbalance & rounding-drift finder", "command": "drift", "description": "Scans sales and purchases for rounding/total drift and VAT-regime breaches using exact integer-øre arithmetic; journal debit/credit imbalance is not checked, because the mirrored journal lines carry no debit/credit direction.", "rationale": "Exact øre math across every journal line in the local mirror — no floating point, no per-entry API calls. Fiken surfaces neither imbalances nor rounding residuals.", "via": "mcp-command-mirror"}, // PATCH(mcp-novel-feature-claims)
			{"name": "VAT-code anomaly detector", "command": "vat-anomaly", "description": "Flags sale/purchase lines whose VAT code is implausible for the account or deviates from how that vendor is usually posted.", "rationale": "Joins lines, accounts, and per-vendor VAT-code history against the embedded Fiken VAT-code table — a cross-entity rule check, not an LLM guess, possible only with the local store.", "via": "mcp-command-mirror"},
			{"name": "MVA / VAT-period summary", "command": "mva-summary", "description": "Reconstructs a VAT-return-shaped view from local lines: net basis and output/input VAT bucketed per VAT code, for any period.", "rationale": "The API has no VAT-summary endpoint; we aggregate the synced sales/purchases lines by VAT type in exact øre.", "via": "mcp-command-mirror"},
			{"name": "Period BI rollup", "command": "rollup", "description": "Grouped revenue/cost/margin rollups over the local mirror by month, account, or contact.", "rationale": "Fiken has no aggregation endpoint; we GROUP BY over synced sales and purchases (joined to contact) with margin computed in exact øre; the mirrored lines carry no project, so there is no project dimension.", "via": "mcp-command-mirror"}, // PATCH(mcp-novel-feature-claims)
			{"name": "Posting proposal builder", "command": "prepare", "description": "Turns an inbox document into a structured posting proposal: pulls the bilag, the vendor's posting history, candidate accounts, and the valid MVA codes in one call.", "rationale": "Compound read over inbox + documentUrl + local vendor history; assembles in one step what otherwise takes several tabs and manual lookup.", "via": "mcp-command-mirror"},
			{"name": "Audited reversal", "command": "reverse", "description": "Reverses a posting with a correcting entry or soft-delete, recording the link back to the original in the audit log.", "rationale": "Pairs with commit's audit trail via reverses_event_id so every correction is traceable — no Fiken tool tracks this.", "via": "mcp-command-mirror"},
			{"name": "Duplicate-posting suspicion", "command": "duplicates", "description": "Surfaces suspected double-postings: the same contact and øre amount within a date window across purchases and sales.", "rationale": "Self-join on the local mirror by (contact, amount, date window) — cheap offline, impossible as a single API call.", "via": "mcp-command-mirror"},
			// PATCH(mcp-reconcile-clearing-claim)
			{"name": "Payment reconciliation", "command": "reconcile", "description": "Registers a payment against an open sale or purchase in NOK, optionally marking a sale settled, and records it in the audit log; it posts no clearing-account journal entries.", "rationale": "Wraps the payments call in a guarded, audited flow; clearing-account entries for payment processors are not composed.", "via": "mcp-command-mirror"},
			{"name": "Audit event sink", "command": "log-event", "description": "Appends a grammar-validated event to the append-only audit log; warns on an unknown operation name but never rejects.", "rationale": "A single audit authority both the CLI and the companion browser harness write to, with structural append-only enforcement.", "via": "mcp-command-mirror"},
			{"name": "Missing-bilag report", "command": "missing-bilag", "description": "Lists postings in a period that have no attached documentation (empty attachments).", "rationale": "A cross-entity filter over the local mirror; the kind of completeness check Fiken's UI makes you do by eye.", "via": "mcp-command-mirror"},
			{"name": "Vendor posting-history profile", "command": "vendor-profile", "description": "Shows how a vendor is usually posted: the modal account and VAT code, with frequency and last-used.", "rationale": "Aggregates the vendor's history in the local store; powers prepare and vat-anomaly and answers 'where does this supplier normally go?'", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Unverified-against-bank detector", "insight": "Requires joining account balances, each bank account's reconciledBalance/reconciledDate, and transactions in the local store — data that only exists together offline; Fiken exposes no such query."},
			{"topic": "Client-side posting validation", "insight": "Fiken has no dry-run; the only way to catch an unbalanced or mis-coded entry today is to post it and see it fail. We check locally against the synced chart of accounts and the embedded VAT-code table."},
			{"topic": "Idempotent audited commit", "insight": "Double-posting real books is unrecoverable; no Fiken tool offers idempotency or an audit trail. Our local core DB makes both structural."},
			{"topic": "Imbalance & rounding-drift finder", "insight": "Exact øre math across every journal line in the local mirror — no floating point, no per-entry API calls. Fiken surfaces neither imbalances nor rounding residuals."},
			{"topic": "VAT-code anomaly detector", "insight": "Joins lines, accounts, and per-vendor VAT-code history against the embedded Fiken VAT-code table — a cross-entity rule check, not an LLM guess, possible only with the local store."},
			{"topic": "MVA / VAT-period summary", "insight": "The API has no VAT-summary endpoint; we aggregate the synced sales/purchases lines by VAT type in exact øre."},
			{"topic": "Period BI rollup", "insight": "Fiken has no aggregation endpoint; we GROUP BY over synced sales and purchases (joined to contact) with margin computed in exact øre; the mirrored lines carry no project, so there is no project dimension."}, // PATCH(mcp-novel-feature-claims)
			{"topic": "Posting proposal builder", "insight": "Compound read over inbox + documentUrl + local vendor history; assembles in one step what otherwise takes several tabs and manual lookup."},
			{"topic": "Audited reversal", "insight": "Pairs with commit's audit trail via reverses_event_id so every correction is traceable — no Fiken tool tracks this."},
			{"topic": "Duplicate-posting suspicion", "insight": "Self-join on the local mirror by (contact, amount, date window) — cheap offline, impossible as a single API call."},
			// PATCH(mcp-reconcile-clearing-claim)
			{"topic": "Payment reconciliation", "insight": "Wraps the payments call (and the sale /settled call) in a guarded, audited flow; it posts no clearing-account journal entries and sends no amountInNok, so foreign-currency payments go through purchases payments create-purchase."},
			{"topic": "Audit event sink", "insight": "A single audit authority both the CLI and the companion browser harness write to, with structural append-only enforcement."},
			{"topic": "Missing-bilag report", "insight": "A cross-entity filter over the local mirror; the kind of completeness check Fiken's UI makes you do by eye."},
			{"topic": "Vendor posting-history profile", "insight": "Aggregates the vendor's history in the local store; powers prepare and vat-anomaly and answers 'where does this supplier normally go?'"},
			{"topic": "Financial data", "insight": "Always use read-only operations for financial queries. Never use create/update tools for payment data without explicit user confirmation."},
			{"topic": "Reconciliation", "insight": "For reconciliation tasks, sync first then use sql for cross-referencing. API pagination over financial records is slow and rate-limited."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
