// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBankAccountsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "bank-accounts",
		Short:       "Get and create bank accounts",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBankAccountsCreateCmd(flags))
	cmd.AddCommand(newBankAccountsGetCmd(flags))
	cmd.AddCommand(newBankAccountsGetCompaniesCmd(flags))
	return cmd
}
