// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newContactsContactPersonUpdateContactCmd(flags *rootFlags) *cobra.Command {
	var bodyAddressCity string
	var bodyAddressCountry string
	var bodyAddressPostCode string
	var bodyAddressStreetAddress string
	var bodyAddressStreetAddressLine2 string
	var bodyContactPersonId2 string
	var bodyEmail string
	var bodyName string
	var bodyPhoneNumber string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-contact <companySlug> <contactId> <contactPersonId>",
		Aliases:     []string{"update"},
		Short:       "Updates an existing contact person.",
		Example:     "  fiken-cli contacts contact-person update-contact example-value 42 42 --email user@example.com",
		Annotations: map[string]string{"pp:endpoint": "contact-person.update-contact", "pp:method": "PUT", "pp:path": "/companies/{companySlug}/contacts/{contactId}/contactPerson/{contactPersonId}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("address-country") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "address-country")
				}
				if !cmd.Flags().Changed("email") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "email")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companySlug}/contacts/{contactId}/contactPerson/{contactPersonId}"
			path = replacePathParam(path, "companySlug", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("contactId is required\nUsage: %s <%s>", cmd.CommandPath(), "contactId"))
			}
			path = replacePathParam(path, "contactId", args[1])
			if len(args) < 3 {
				return usageErr(fmt.Errorf("contactPersonId is required\nUsage: %s <%s>", cmd.CommandPath(), "contactPersonId"))
			}
			path = replacePathParam(path, "contactPersonId", args[2])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedAddress := map[string]any{}
					if bodyAddressCity != "" {
						nestedAddress["city"] = bodyAddressCity
					}
					if bodyAddressCountry != "" {
						nestedAddress["country"] = bodyAddressCountry
					}
					if bodyAddressPostCode != "" {
						nestedAddress["postCode"] = bodyAddressPostCode
					}
					if bodyAddressStreetAddress != "" {
						nestedAddress["streetAddress"] = bodyAddressStreetAddress
					}
					if bodyAddressStreetAddressLine2 != "" {
						nestedAddress["streetAddressLine2"] = bodyAddressStreetAddressLine2
					}
					if len(nestedAddress) > 0 {
						body["address"] = nestedAddress
					}
				}
				if bodyContactPersonId2 != "" {
					body["contactPersonId"] = bodyContactPersonId2
				}
				if bodyEmail != "" {
					body["email"] = bodyEmail
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyPhoneNumber != "" {
					body["phoneNumber"] = bodyPhoneNumber
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "contact-person", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				// PATCH(mutation-cache-parent-id): request path threaded in so the cached
				// mutation row is stamped with parent_id and keyed per company.
				writeMutationResponseToStore(cmd.Context(), "contact-person", data, "", path)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "contact-person", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "contact-person", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "contact-person", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "contact-person",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "contact-person", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "contact-person", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAddressCity, "address-city", "", "City")
	cmd.Flags().StringVar(&bodyAddressCountry, "address-country", "", "Country")
	cmd.Flags().StringVar(&bodyAddressPostCode, "address-post-code", "", "Post code")
	cmd.Flags().StringVar(&bodyAddressStreetAddress, "address-street-address", "", "Street address")
	cmd.Flags().StringVar(&bodyAddressStreetAddressLine2, "address-street-address-line2", "", "Street address line2")
	cmd.Flags().StringVar(&bodyContactPersonId2, "contact-person-id-2", "", "Contact person id")
	cmd.Flags().StringVar(&bodyEmail, "email", "", "Email")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")
	cmd.Flags().StringVar(&bodyPhoneNumber, "phone-number", "", "Phone number")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
