// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCreditNotesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "credit-notes",
		Short:       "Get, create, add, update, delete, and send credit notes",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCreditNotesAddAttachmentToDraftCmd(flags))
	cmd.AddCommand(newCreditNotesCreateCounterCmd(flags))
	cmd.AddCommand(newCreditNotesCreateDraftCmd(flags))
	cmd.AddCommand(newCreditNotesCreateFromDraftCmd(flags))
	cmd.AddCommand(newCreditNotesCreateFullCmd(flags))
	cmd.AddCommand(newCreditNotesCreatePartialCmd(flags))
	cmd.AddCommand(newCreditNotesDeleteDraftCmd(flags))
	cmd.AddCommand(newCreditNotesGetCmd(flags))
	cmd.AddCommand(newCreditNotesGetCompaniesCmd(flags))
	cmd.AddCommand(newCreditNotesGetCounterCmd(flags))
	cmd.AddCommand(newCreditNotesGetDraftCmd(flags))
	cmd.AddCommand(newCreditNotesGetDraftAttachmentsCmd(flags))
	cmd.AddCommand(newCreditNotesGetDraftsCmd(flags))
	cmd.AddCommand(newCreditNotesSendCmd(flags))
	cmd.AddCommand(newCreditNotesUpdateDraftCmd(flags))
	return cmd
}
