// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCreditNotesCreateDraftCmd(flags *rootFlags) *cobra.Command {
	var bodyBankAccountNumber string
	var bodyBic string
	var bodyContactPersonId string
	var bodyCurrency string
	var bodyCustomerId string
	var bodyDaysUntilDueDate int
	var bodyIban string
	var bodyInvoiceText string
	var bodyIssueDate string
	var bodyLines string
	var bodyOrderReference string
	var bodyOurReference string
	var bodyPaymentAccount string
	var bodyProjectId string
	var bodyRoundingType string
	var bodyType string
	var bodyUuid string
	var bodyYourReference string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-draft <companySlug>",
		Short:       "Creates a credit note draft. This draft corresponds to a draft for an 'uavhengig kreditnota' in Fiken.",
		Example:     "  fiken-cli credit-notes create-draft example-value --type invoice",
		Annotations: map[string]string{"pp:endpoint": "credit-notes.create-draft", "pp:method": "POST", "pp:path": "/companies/{companySlug}/creditNotes/drafts"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("customer-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "customer-id")
				}
				if !cmd.Flags().Changed("days-until-due-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "days-until-due-date")
				}
				if !cmd.Flags().Changed("type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companySlug}/creditNotes/drafts"
			path = replacePathParam(path, "companySlug", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyBankAccountNumber != "" {
					body["bankAccountNumber"] = bodyBankAccountNumber
				}
				if bodyBic != "" {
					body["bic"] = bodyBic
				}
				if bodyContactPersonId != "" {
					body["contactPersonId"] = bodyContactPersonId
				}
				if bodyCurrency != "" {
					body["currency"] = bodyCurrency
				}
				if bodyCustomerId != "" {
					body["customerId"] = bodyCustomerId
				}
				if bodyDaysUntilDueDate != 0 {
					body["daysUntilDueDate"] = bodyDaysUntilDueDate
				}
				if bodyIban != "" {
					body["iban"] = bodyIban
				}
				if bodyInvoiceText != "" {
					body["invoiceText"] = bodyInvoiceText
				}
				if bodyIssueDate != "" {
					body["issueDate"] = bodyIssueDate
				}
				if bodyLines != "" {
					var parsedLines any
					if err := json.Unmarshal([]byte(bodyLines), &parsedLines); err != nil {
						return fmt.Errorf("parsing --lines JSON: %w", err)
					}
					body["lines"] = parsedLines
				}
				if bodyOrderReference != "" {
					body["orderReference"] = bodyOrderReference
				}
				if bodyOurReference != "" {
					body["ourReference"] = bodyOurReference
				}
				if bodyPaymentAccount != "" {
					body["paymentAccount"] = bodyPaymentAccount
				}
				if bodyProjectId != "" {
					body["projectId"] = bodyProjectId
				}
				if bodyRoundingType != "" {
					body["roundingType"] = bodyRoundingType
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
				if bodyUuid != "" {
					body["uuid"] = bodyUuid
				}
				if bodyYourReference != "" {
					body["yourReference"] = bodyYourReference
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "credit-notes", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "credit-notes", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "credit-notes", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "credit-notes", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "credit-notes", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "credit-notes",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "credit-notes", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "credit-notes", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyBankAccountNumber, "bank-account-number", "", "Bank account number")
	cmd.Flags().StringVar(&bodyBic, "bic", "", "Bic")
	cmd.Flags().StringVar(&bodyContactPersonId, "contact-person-id", "", "Id of the contact person. Must be associated with the provided customer.")
	cmd.Flags().StringVar(&bodyCurrency, "currency", "", "ISO 4217 currency code")
	cmd.Flags().StringVar(&bodyCustomerId, "customer-id", "", "customerId = contactId where customer = true")
	cmd.Flags().IntVar(&bodyDaysUntilDueDate, "days-until-due-date", 0, "Days until due date of the invoice draft.")
	cmd.Flags().StringVar(&bodyIban, "iban", "", "Iban")
	cmd.Flags().StringVar(&bodyInvoiceText, "invoice-text", "", "Comment/description printed above the invoice lines.")
	cmd.Flags().StringVar(&bodyIssueDate, "issue-date", "", "Issue date of the invoice draft, format yyyy-mm-dd")
	cmd.Flags().StringVar(&bodyLines, "lines", "", "Lines")
	cmd.Flags().StringVar(&bodyOrderReference, "order-reference", "", "Reference if sending invoice via EHF.")
	cmd.Flags().StringVar(&bodyOurReference, "our-reference", "", "Our reference")
	cmd.Flags().StringVar(&bodyPaymentAccount, "payment-account", "", "Payment account")
	cmd.Flags().StringVar(&bodyProjectId, "project-id", "", "Project id")
	cmd.Flags().StringVar(&bodyRoundingType, "rounding-type", "", "Type of øreavrunding (rounding) to apply to the total. 'none' means no rounding (default).")
	cmd.Flags().StringVar(&bodyType, "type", "", "Type of draft.")
	cmd.Flags().StringVar(&bodyUuid, "uuid", "", "UUID are represented as 32 hexadecimal (base-16) digits, displayed in 5 groups separated by hyphens")
	cmd.Flags().StringVar(&bodyYourReference, "your-reference", "", "Your reference")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
