// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newInboxGetCmd(flags *rootFlags) *cobra.Command {
	var flagPage string
	var flagPageSize int
	var flagSortBy string
	var flagStatus string
	var flagName string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get <companySlug>",
		Short:       "Returns the contents of the inbox for given company.",
		Example:     "  fiken-cli inbox get example-value",
		Annotations: map[string]string{"pp:endpoint": "inbox.get", "pp:method": "GET", "pp:path": "/companies/{companySlug}/inbox", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("sort-by") {
				allowedSortBy := []string{"createdDate asc", "createdDate desc", "name asc", "name desc"}
				validSortBy := false
				for _, v := range allowedSortBy {
					if flagSortBy == v {
						validSortBy = true
						break
					}
				}
				if !validSortBy {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagSortBy, "sort-by", allowedSortBy)
				}
			}
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"all", "unused", "used"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagStatus, "status", allowedStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companySlug}/inbox"
			path = replacePathParam(path, "companySlug", args[0])
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "inbox", path, map[string]string{
				"page":     formatCLIParamValue(flagPage),
				"pageSize": formatCLIParamValue(flagPageSize),
				"sortBy":   formatCLIParamValue(flagSortBy),
				"status":   formatCLIParamValue(flagStatus),
				"name":     formatCLIParamValue(flagName),
			}, nil, flagAll, "page", "page", "pageSize", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPage, "page", "0", "Returns the number of the page to return. Valid page values are integers from 0 to the total number of pages.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 25, "Defines the number of entries to return on each page.")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "createdDate desc", "Sorts results in either ascending (asc) or descending (desc) order based on the parameter value. (one of: createdDate asc, createdDate desc, name asc, name desc)")
	cmd.Flags().StringVar(&flagStatus, "status", "all", "Status (one of: all, unused, used)")
	cmd.Flags().StringVar(&flagName, "name", "", "Filter documents based on their name, case-insensitive substring match.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
