// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInboxCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "inbox",
		Short:       "Get, create, and delete inbox",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newInboxCreateDocumentCmd(flags))
	cmd.AddCommand(newInboxDeleteDocumentCmd(flags))
	cmd.AddCommand(newInboxGetCmd(flags))
	cmd.AddCommand(newInboxGetDocumentCmd(flags))
	return cmd
}
