// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInvoicesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "invoices",
		Short:       "Get, create, add, update, delete, and send invoices",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newInvoicesAddAttachmentToDraftCmd(flags))
	cmd.AddCommand(newInvoicesCreateCmd(flags))
	cmd.AddCommand(newInvoicesCreateCounterCmd(flags))
	cmd.AddCommand(newInvoicesCreateDraftCmd(flags))
	cmd.AddCommand(newInvoicesCreateFromDraftCmd(flags))
	cmd.AddCommand(newInvoicesDeleteDraftCmd(flags))
	cmd.AddCommand(newInvoicesGetCmd(flags))
	cmd.AddCommand(newInvoicesGetCompaniesCmd(flags))
	cmd.AddCommand(newInvoicesGetCounterCmd(flags))
	cmd.AddCommand(newInvoicesGetDraftCmd(flags))
	cmd.AddCommand(newInvoicesGetDraftAttachmentsCmd(flags))
	cmd.AddCommand(newInvoicesGetDraftsCmd(flags))
	cmd.AddCommand(newInvoicesSendCmd(flags))
	cmd.AddCommand(newInvoicesUpdateCmd(flags))
	cmd.AddCommand(newInvoicesUpdateDraftCmd(flags))
	cmd.AddCommand(newInvoicesAttachmentsCmd(flags))
	return cmd
}
