// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newInvoicesGetCmd(flags *rootFlags) *cobra.Command {
	var flagPage string
	var flagPageSize int
	var flagIssueDate string
	var flagIssueDateLe string
	var flagIssueDateLt string
	var flagIssueDateGe string
	var flagIssueDateGt string
	var flagLastModified string
	var flagLastModifiedLe string
	var flagLastModifiedLt string
	var flagLastModifiedGe string
	var flagLastModifiedGt string
	var flagDueDate string
	var flagDueDateLe string
	var flagDueDateLt string
	var flagDueDateGe string
	var flagDueDateGt string
	var flagCustomerId string
	var flagSettled bool
	var flagOrderReference string
	var flagInvoiceDraftUuid string
	var flagInvoiceNumber string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get <companySlug>",
		Short:       "Returns all invoices for given company.",
		Example:     "  fiken-cli invoices get example-value",
		Annotations: map[string]string{"pp:endpoint": "invoices.get", "pp:method": "GET", "pp:path": "/companies/{companySlug}/invoices", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companySlug}/invoices"
			path = replacePathParam(path, "companySlug", args[0])
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "invoices", path, map[string]string{
				"page":             formatCLIParamValue(flagPage),
				"pageSize":         formatCLIParamValue(flagPageSize),
				"issueDate":        formatCLIParamValue(flagIssueDate),
				"issueDateLe":      formatCLIParamValue(flagIssueDateLe),
				"issueDateLt":      formatCLIParamValue(flagIssueDateLt),
				"issueDateGe":      formatCLIParamValue(flagIssueDateGe),
				"issueDateGt":      formatCLIParamValue(flagIssueDateGt),
				"lastModified":     formatCLIParamValue(flagLastModified),
				"lastModifiedLe":   formatCLIParamValue(flagLastModifiedLe),
				"lastModifiedLt":   formatCLIParamValue(flagLastModifiedLt),
				"lastModifiedGe":   formatCLIParamValue(flagLastModifiedGe),
				"lastModifiedGt":   formatCLIParamValue(flagLastModifiedGt),
				"dueDate":          formatCLIParamValue(flagDueDate),
				"dueDateLe":        formatCLIParamValue(flagDueDateLe),
				"dueDateLt":        formatCLIParamValue(flagDueDateLt),
				"dueDateGe":        formatCLIParamValue(flagDueDateGe),
				"dueDateGt":        formatCLIParamValue(flagDueDateGt),
				"customerId":       formatCLIParamValue(flagCustomerId),
				"settled":          formatCLIParamValue(flagSettled),
				"orderReference":   formatCLIParamValue(flagOrderReference),
				"invoiceDraftUuid": formatCLIParamValue(flagInvoiceDraftUuid),
				"invoiceNumber":    formatCLIParamValue(flagInvoiceNumber),
			}, nil, flagAll, "page", "page", "pageSize", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPage, "page", "0", "Returns the number of the page to return. Valid page values are integers from 0 to the total number of pages.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 25, "Defines the number of entries to return on each page.")
	cmd.Flags().StringVar(&flagIssueDate, "issue-date", "", "Dates are represented as strings formatted as YYYY-MM-DD. Example: January 1st, 1970: '1970-01-01'")
	cmd.Flags().StringVar(&flagIssueDateLe, "issue-date-le", "", "Filter based on date less than or equal to parameter value. Dates are represented as strings formatted as YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagIssueDateLt, "issue-date-lt", "", "Filter based on date strictly less than parameter value. Dates are represented as strings formatted as YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagIssueDateGe, "issue-date-ge", "", "Filter based on date greater than or equal to parameter value. Dates are represented as strings formatted as YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagIssueDateGt, "issue-date-gt", "", "Filter based on date strictly greater than parameter value Dates are represented as strings formatted as YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagLastModified, "last-modified", "", "Filter based on date of last modification.")
	cmd.Flags().StringVar(&flagLastModifiedLe, "last-modified-le", "", "Returns results that have been last modified before or on the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagLastModifiedLt, "last-modified-lt", "", "Returns results that have been last modified strictly before the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagLastModifiedGe, "last-modified-ge", "", "Returns results that have been last modified after or on the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagLastModifiedGt, "last-modified-gt", "", "Returns results that have been last modified strictly after the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagDueDate, "due-date", "", "Filter based on due date of invoice. Returns results from the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagDueDateLe, "due-date-le", "", "Returns invoices with a due date before or on the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagDueDateLt, "due-date-lt", "", "Returns invoices with a due date that have been last modified strictly before the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagDueDateGe, "due-date-ge", "", "Returns invoices with a due date that have been last modified after or on the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagDueDateGt, "due-date-gt", "", "Returns invoices with a due date that have been last modified strictly after the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagCustomerId, "customer-id", "", "Returns only invoices sent to specified customer. Must be the contactId provided by a GET contacts call.")
	cmd.Flags().BoolVar(&flagSettled, "settled", false, "When set to true, returns only invoices that have been settled.")
	cmd.Flags().StringVar(&flagOrderReference, "order-reference", "", "Filter based on order reference for a given invoice")
	cmd.Flags().StringVar(&flagInvoiceDraftUuid, "invoice-draft-uuid", "", "Filter based on the UUID of the invoice draft that was used to create a given invoice")
	cmd.Flags().StringVar(&flagInvoiceNumber, "invoice-number", "", "Invoice number")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
