// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
)

func newInvoicesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyBankAccountCode string
	var bodyCash string
	var bodyContactPersonId string
	var bodyCurrency string
	var bodyCustomerId string
	var bodyDueDate string
	var bodyInvoiceText string
	var bodyIssueDate string
	var bodyLines string
	var bodyOrderReference string
	var bodyOurReference string
	var bodyPaymentAccount string
	var bodyProjectId string
	var bodyRoundingType string
	var bodyUuid string
	var bodyYourReference string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <companySlug>",
		Short:       "Creates an invoice. This corresponds to 'Ny faktura' in Fiken.",
		Example:     "  fiken-cli invoices create example-value --bank-account-code example-value",
		Annotations: map[string]string{"pp:endpoint": "invoices.create", "pp:method": "POST", "pp:path": "/companies/{companySlug}/invoices"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("bank-account-code") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "bank-account-code")
				}
				if !cmd.Flags().Changed("cash") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "cash")
				}
				if !cmd.Flags().Changed("customer-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "customer-id")
				}
				if !cmd.Flags().Changed("due-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "due-date")
				}
				if !cmd.Flags().Changed("issue-date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "issue-date")
				}
				if !cmd.Flags().Changed("lines") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "lines")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companySlug}/invoices"
			path = replacePathParam(path, "companySlug", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyBankAccountCode != "" {
					body["bankAccountCode"] = bodyBankAccountCode
				}
				if bodyCash != "" {
					parsedCash, err := strconv.ParseBool(bodyCash)
					if err != nil {
						return fmt.Errorf("parsing --cash as bool: %w", err)
					}
					body["cash"] = parsedCash
				}
				if bodyContactPersonId != "" {
					body["contactPersonId"] = bodyContactPersonId
				}
				if bodyCurrency != "" {
					body["currency"] = bodyCurrency
				}
				if bodyCustomerId != "" {
					body["customerId"] = bodyCustomerId
				}
				if bodyDueDate != "" {
					body["dueDate"] = bodyDueDate
				}
				if bodyInvoiceText != "" {
					body["invoiceText"] = bodyInvoiceText
				}
				if bodyIssueDate != "" {
					body["issueDate"] = bodyIssueDate
				}
				if bodyLines != "" {
					var parsedLines any
					if err := json.Unmarshal([]byte(bodyLines), &parsedLines); err != nil {
						return fmt.Errorf("parsing --lines JSON: %w", err)
					}
					body["lines"] = parsedLines
				}
				if bodyOrderReference != "" {
					body["orderReference"] = bodyOrderReference
				}
				if bodyOurReference != "" {
					body["ourReference"] = bodyOurReference
				}
				if bodyPaymentAccount != "" {
					body["paymentAccount"] = bodyPaymentAccount
				}
				if bodyProjectId != "" {
					body["projectId"] = bodyProjectId
				}
				if bodyRoundingType != "" {
					body["roundingType"] = bodyRoundingType
				}
				if bodyUuid != "" {
					body["uuid"] = bodyUuid
				}
				if bodyYourReference != "" {
					body["yourReference"] = bodyYourReference
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "invoices", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				// PATCH(mutation-cache-parent-id): request path threaded in so the cached
				// mutation row is stamped with parent_id and keyed per company.
				writeMutationResponseToStore(cmd.Context(), "invoices", data, "", path)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "invoices", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "invoices", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "invoices", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "invoices",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "invoices", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "invoices", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyBankAccountCode, "bank-account-code", "", "Bank account code associated with invoice, format 1920:XXXXX")
	cmd.Flags().StringVar(&bodyCash, "cash", "", "Payment taken in cash (True) or not (False).")
	cmd.Flags().StringVar(&bodyContactPersonId, "contact-person-id", "", "Id of the contact person. Must be associated with the provided customer.")
	cmd.Flags().StringVar(&bodyCurrency, "currency", "", "ISO 4217 currency code. Defaults to 'NOK' if unspecified.")
	cmd.Flags().StringVar(&bodyCustomerId, "customer-id", "", "customerId = contactId where customer = true")
	cmd.Flags().StringVar(&bodyDueDate, "due-date", "", "Due date of invoice, format yyyy-mm-dd")
	cmd.Flags().StringVar(&bodyInvoiceText, "invoice-text", "", "If not present, and standard text is registered, standard text is printed.")
	cmd.Flags().StringVar(&bodyIssueDate, "issue-date", "", "Date that the invoice was issued, format yyyy-mm-dd")
	cmd.Flags().StringVar(&bodyLines, "lines", "", "Lines")
	cmd.Flags().StringVar(&bodyOrderReference, "order-reference", "", "Reference if sending via EHF.")
	cmd.Flags().StringVar(&bodyOurReference, "our-reference", "", "Our reference")
	cmd.Flags().StringVar(&bodyPaymentAccount, "payment-account", "", "For Cash Invoices only. For instance '1920:10001'.")
	cmd.Flags().StringVar(&bodyProjectId, "project-id", "", "Optional - Associated project for the invoice to be created.")
	cmd.Flags().StringVar(&bodyRoundingType, "rounding-type", "", "Type of øreavrunding (rounding) to apply to the total. 'none' means no rounding (default).")
	cmd.Flags().StringVar(&bodyUuid, "uuid", "", "UUID are represented as 32 hexadecimal (base-16) digits, displayed in 5 groups separated by hyphens")
	cmd.Flags().StringVar(&bodyYourReference, "your-reference", "", "Your reference for invoice, free string format")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
