// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newJournalEntriesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "journal-entries",
		Short:       "Manage journal entries command groups",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newJournalEntriesGetCmd(flags))
	cmd.AddCommand(newJournalEntriesGetJournalEntryCmd(flags))
	cmd.AddCommand(newJournalEntriesAttachmentsCmd(flags))
	return cmd
}
