// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newJournalEntriesAttachmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "attachments",
		Short:       "Get and add attachments for journal entries",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newJournalEntriesAttachmentsAddToJournalEntryCmd(flags))
	cmd.AddCommand(newJournalEntriesAttachmentsGetJournalEntryCmd(flags))
	return cmd
}
