// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOffersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "offers",
		Short:       "Get, create, add, update, delete, and send offers",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOffersAddAttachmentToDraftCmd(flags))
	cmd.AddCommand(newOffersCreateCounterCmd(flags))
	cmd.AddCommand(newOffersCreateDraftCmd(flags))
	cmd.AddCommand(newOffersCreateFromDraftCmd(flags))
	cmd.AddCommand(newOffersDeleteDraftCmd(flags))
	cmd.AddCommand(newOffersGetCmd(flags))
	cmd.AddCommand(newOffersGetCompaniesCmd(flags))
	cmd.AddCommand(newOffersGetCounterCmd(flags))
	cmd.AddCommand(newOffersGetDraftCmd(flags))
	cmd.AddCommand(newOffersGetDraftAttachmentsCmd(flags))
	cmd.AddCommand(newOffersGetDraftsCmd(flags))
	cmd.AddCommand(newOffersSendCmd(flags))
	cmd.AddCommand(newOffersUpdateDraftCmd(flags))
	return cmd
}
