// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrderConfirmationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "order-confirmations",
		Short:       "Get, create, add, update, and delete order confirmations",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrderConfirmationsAddAttachmentToDraftCmd(flags))
	cmd.AddCommand(newOrderConfirmationsCreateCounterCmd(flags))
	cmd.AddCommand(newOrderConfirmationsCreateDraftCmd(flags))
	cmd.AddCommand(newOrderConfirmationsCreateFromDraftCmd(flags))
	cmd.AddCommand(newOrderConfirmationsDeleteDraftCmd(flags))
	cmd.AddCommand(newOrderConfirmationsGetCmd(flags))
	cmd.AddCommand(newOrderConfirmationsGetCompaniesCmd(flags))
	cmd.AddCommand(newOrderConfirmationsGetCounterCmd(flags))
	cmd.AddCommand(newOrderConfirmationsGetDraftCmd(flags))
	cmd.AddCommand(newOrderConfirmationsGetDraftAttachmentsCmd(flags))
	cmd.AddCommand(newOrderConfirmationsGetDraftsCmd(flags))
	cmd.AddCommand(newOrderConfirmationsUpdateDraftCmd(flags))
	cmd.AddCommand(newOrderConfirmationsCreateInvoiceDraftCmd(flags))
	return cmd
}
