// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrderConfirmationsCreateInvoiceDraftCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "create-invoice-draft",
		Short:       "Manage create invoice draft",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrderConfirmationsCreateInvoiceDraftFromOrderConfirmationCmd(flags))
	return cmd
}
