// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProductsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "products",
		Short:       "Get, create, update, and delete products",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProductsCreateCmd(flags))
	cmd.AddCommand(newProductsCreateSalesReportCmd(flags))
	cmd.AddCommand(newProductsDeleteCmd(flags))
	cmd.AddCommand(newProductsGetCmd(flags))
	cmd.AddCommand(newProductsGetCompaniesCmd(flags))
	cmd.AddCommand(newProductsUpdateCmd(flags))
	return cmd
}
