// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGeneralJournalEntriesPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyDescription string
	var bodyJournalEntries string
	var bodyOpen bool

	cmd := &cobra.Command{
		Use:         "general-journal-entries <companySlug>",
		Short:       "Creates a new general journal entry (fri postering).",
		Long:        "Creates a new general journal entry (fri postering).",
		Example:     "  fiken-cli general-journal-entries example-value",
		Annotations: map[string]string{"pp:endpoint": "general-journal-entries.create-general-journal-entry", "pp:method": "POST", "pp:path": "/companies/{companySlug}/generalJournalEntries"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("journal-entries") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "journal-entries")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companySlug}/generalJournalEntries"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "companySlug is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "companySlug"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("companySlug is required\nUsage: %s <%s>", cmd.CommandPath(), "companySlug"))
			}
			path = replacePathParam(path, "companySlug", args[0])
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyDescription != "" {
				body["description"] = bodyDescription
			}
			if bodyJournalEntries != "" {
				var parsedJournalEntries any
				if err := json.Unmarshal([]byte(bodyJournalEntries), &parsedJournalEntries); err != nil {
					return fmt.Errorf("parsing --journal-entries JSON: %w", err)
				}
				body["journalEntries"] = parsedJournalEntries
			}
			if cmd.Flags().Changed("open") {
				body["open"] = bodyOpen
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				// PATCH(mutation-cache-parent-id): request path threaded in so the cached
				// mutation row is stamped with parent_id and keyed per company.
				writeMutationResponseToStore(cmd.Context(), "general-journal-entries", data, "", path)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDescription, "description", "", "We add the flag 'Fri postering registrert via API: '.")
	cmd.Flags().StringVar(&bodyJournalEntries, "journal-entries", "", "Journal entries")
	cmd.Flags().BoolVar(&bodyOpen, "open", false, "The journal entry can be set to either open or closed (closed is the default).")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
