// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newBankBalancesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPage string
	var flagPageSize int
	var flagDate string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "bank-balances <companySlug>",
		Short:       "Retrieves all bank balances for the specified company.",
		Long:        "Retrieves all bank balances for the specified company.",
		Example:     "  fiken-cli bank-balances example-value",
		Annotations: map[string]string{"pp:endpoint": "bank-balances.get", "pp:method": "GET", "pp:path": "/companies/{companySlug}/bankBalances", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companySlug}/bankBalances"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "companySlug is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "companySlug"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("companySlug is required\nUsage: %s <%s>", cmd.CommandPath(), "companySlug"))
			}
			path = replacePathParam(path, "companySlug", args[0])
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "bank-balances", path, map[string]string{
				"page":     formatCLIParamValue(flagPage),
				"pageSize": formatCLIParamValue(flagPageSize),
				"date":     formatCLIParamValue(flagDate),
			}, nil, flagAll, "page", "page", "pageSize", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPage, "page", "0", "Returns the number of the page to return. Valid page values are integers from 0 to the total number of pages.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 25, "Defines the number of entries to return on each page.")
	cmd.Flags().StringVar(&flagDate, "date", "", "Dates are represented as strings formatted as YYYY-MM-DD. Example: January 1st, 1970: '1970-01-01'")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
