// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPurchasesPaymentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "payments",
		Short:       "Get and create payments for purchases",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPurchasesPaymentsCreatePurchaseCmd(flags))
	cmd.AddCommand(newPurchasesPaymentsGetPurchaseCmd(flags))
	cmd.AddCommand(newPurchasesPaymentsGetPurchaseCompaniesCmd(flags))
	return cmd
}
