// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPurchasesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "purchases",
		Short:       "Get, create, add, update, and delete purchases",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPurchasesAddAttachmentToDraftCmd(flags))
	cmd.AddCommand(newPurchasesCreateCmd(flags))
	cmd.AddCommand(newPurchasesCreateDraftCmd(flags))
	cmd.AddCommand(newPurchasesCreateFromDraftCmd(flags))
	cmd.AddCommand(newPurchasesDeleteDraftCmd(flags))
	cmd.AddCommand(newPurchasesGetCmd(flags))
	cmd.AddCommand(newPurchasesGetCompaniesCmd(flags))
	cmd.AddCommand(newPurchasesGetDraftCmd(flags))
	cmd.AddCommand(newPurchasesGetDraftAttachmentsCmd(flags))
	cmd.AddCommand(newPurchasesGetDraftsCmd(flags))
	cmd.AddCommand(newPurchasesUpdateDraftCmd(flags))
	cmd.AddCommand(newPurchasesAttachmentsCmd(flags))
	cmd.AddCommand(newPurchasesDeleteCmd(flags))
	cmd.AddCommand(newPurchasesPaymentsCmd(flags))
	return cmd
}
