// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newPurchasesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyCurrency string
	var bodyDate string
	var bodyDueDate string
	var bodyIdentifier string
	var bodyKid string
	var bodyKind string
	var bodyLines string
	var bodyPaymentAccount string
	var bodyPaymentAmountInNok int
	var bodyPaymentDate string
	var bodyProjectId string
	var bodySupplierId string
	var bodyTransactionId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <companySlug>",
		Short:       "Creates a new purchase.",
		Example:     "  fiken-cli purchases create example-value --currency example-value",
		Annotations: map[string]string{"pp:endpoint": "purchases.create", "pp:method": "POST", "pp:path": "/companies/{companySlug}/purchases"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("currency") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "currency")
				}
				if !cmd.Flags().Changed("date") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "date")
				}
				if !cmd.Flags().Changed("kind") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "kind")
				}
				if !cmd.Flags().Changed("lines") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "lines")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companySlug}/purchases"
			path = replacePathParam(path, "companySlug", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCurrency != "" {
					body["currency"] = bodyCurrency
				}
				if bodyDate != "" {
					body["date"] = bodyDate
				}
				if bodyDueDate != "" {
					body["dueDate"] = bodyDueDate
				}
				if bodyIdentifier != "" {
					body["identifier"] = bodyIdentifier
				}
				if bodyKid != "" {
					body["kid"] = bodyKid
				}
				if bodyKind != "" {
					body["kind"] = bodyKind
				}
				if bodyLines != "" {
					var parsedLines any
					if err := json.Unmarshal([]byte(bodyLines), &parsedLines); err != nil {
						return fmt.Errorf("parsing --lines JSON: %w", err)
					}
					body["lines"] = parsedLines
				}
				if bodyPaymentAccount != "" {
					body["paymentAccount"] = bodyPaymentAccount
				}
				if bodyPaymentAmountInNok != 0 {
					body["paymentAmountInNok"] = bodyPaymentAmountInNok
				}
				if bodyPaymentDate != "" {
					body["paymentDate"] = bodyPaymentDate
				}
				if bodyProjectId != "" {
					body["projectId"] = bodyProjectId
				}
				if bodySupplierId != "" {
					body["supplierId"] = bodySupplierId
				}
				if bodyTransactionId != "" {
					body["transactionId"] = bodyTransactionId
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "purchases", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "purchases", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "purchases", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "purchases", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "purchases", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "purchases",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "purchases", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "purchases", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyCurrency, "currency", "", "ISO 4217 currency code")
	cmd.Flags().StringVar(&bodyDate, "date", "", "Payment date, format yyyy-mm-dd")
	cmd.Flags().StringVar(&bodyDueDate, "due-date", "", "Due date of the invoice, format yyyy-mm-dd")
	cmd.Flags().StringVar(&bodyIdentifier, "identifier", "", "Invoice/sale number or similar.")
	cmd.Flags().StringVar(&bodyKid, "kid", "", "Norwegian KID number. Number from 2 to 25 digits long.")
	cmd.Flags().StringVar(&bodyKind, "kind", "", "Purchased with cash or through a supplier.")
	cmd.Flags().StringVar(&bodyLines, "lines", "", "Lines")
	cmd.Flags().StringVar(&bodyPaymentAccount, "payment-account", "", "Payment account")
	cmd.Flags().IntVar(&bodyPaymentAmountInNok, "payment-amount-in-nok", 0, "Required when creating a purchase with payment in a foreign currency.")
	cmd.Flags().StringVar(&bodyPaymentDate, "payment-date", "", "Payment date, format yyyy-mm-dd")
	cmd.Flags().StringVar(&bodyProjectId, "project-id", "", "Id of given project.")
	cmd.Flags().StringVar(&bodySupplierId, "supplier-id", "", "Id of supplier if not a cash purchase.")
	cmd.Flags().StringVar(&bodyTransactionId, "transaction-id", "", "Transaction id")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
