// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSalesPaymentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "payments",
		Short:       "Get and create payments for sales",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSalesPaymentsCreateSaleCmd(flags))
	cmd.AddCommand(newSalesPaymentsGetSaleCmd(flags))
	cmd.AddCommand(newSalesPaymentsGetSaleCompaniesCmd(flags))
	return cmd
}
