// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSalesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sales",
		Short:       "Get, create, add, update, and delete sales",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSalesAddAttachmentToDraftCmd(flags))
	cmd.AddCommand(newSalesCreateCmd(flags))
	cmd.AddCommand(newSalesCreateDraftCmd(flags))
	cmd.AddCommand(newSalesCreateFromDraftCmd(flags))
	cmd.AddCommand(newSalesDeleteDraftCmd(flags))
	cmd.AddCommand(newSalesGetCmd(flags))
	cmd.AddCommand(newSalesGetCompaniesCmd(flags))
	cmd.AddCommand(newSalesGetDraftCmd(flags))
	cmd.AddCommand(newSalesGetDraftAttachmentsCmd(flags))
	cmd.AddCommand(newSalesGetDraftsCmd(flags))
	cmd.AddCommand(newSalesUpdateDraftCmd(flags))
	cmd.AddCommand(newSalesAttachmentsCmd(flags))
	cmd.AddCommand(newSalesDeleteCmd(flags))
	cmd.AddCommand(newSalesPaymentsCmd(flags))
	cmd.AddCommand(newSalesSettledCmd(flags))
	cmd.AddCommand(newSalesWriteOffCmd(flags))
	return cmd
}
