// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSalesGetCmd(flags *rootFlags) *cobra.Command {
	var flagPage string
	var flagPageSize int
	var flagDate string
	var flagDateLe string
	var flagDateLt string
	var flagDateGe string
	var flagDateGt string
	var flagLastModified string
	var flagLastModifiedLe string
	var flagLastModifiedLt string
	var flagLastModifiedGe string
	var flagLastModifiedGt string
	var flagSaleNumber string
	var flagSettled bool
	var flagContactId string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get <companySlug>",
		Short:       "Returns all sales for given company",
		Example:     "  fiken-cli sales get example-value",
		Annotations: map[string]string{"pp:endpoint": "sales.get", "pp:method": "GET", "pp:path": "/companies/{companySlug}/sales", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/companies/{companySlug}/sales"
			path = replacePathParam(path, "companySlug", args[0])
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "auto", "sales", path, map[string]string{
				"page":           formatCLIParamValue(flagPage),
				"pageSize":       formatCLIParamValue(flagPageSize),
				"date":           formatCLIParamValue(flagDate),
				"dateLe":         formatCLIParamValue(flagDateLe),
				"dateLt":         formatCLIParamValue(flagDateLt),
				"dateGe":         formatCLIParamValue(flagDateGe),
				"dateGt":         formatCLIParamValue(flagDateGt),
				"lastModified":   formatCLIParamValue(flagLastModified),
				"lastModifiedLe": formatCLIParamValue(flagLastModifiedLe),
				"lastModifiedLt": formatCLIParamValue(flagLastModifiedLt),
				"lastModifiedGe": formatCLIParamValue(flagLastModifiedGe),
				"lastModifiedGt": formatCLIParamValue(flagLastModifiedGt),
				"saleNumber":     formatCLIParamValue(flagSaleNumber),
				"settled":        formatCLIParamValue(flagSettled),
				"contactId":      formatCLIParamValue(flagContactId),
			}, nil, flagAll, "page", "page", "pageSize", "", "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPage, "page", "0", "Returns the number of the page to return. Valid page values are integers from 0 to the total number of pages.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 25, "Defines the number of entries to return on each page.")
	cmd.Flags().StringVar(&flagDate, "date", "", "Dates are represented as strings formatted as YYYY-MM-DD. Example: January 1st, 1970: '1970-01-01'")
	cmd.Flags().StringVar(&flagDateLe, "date-le", "", "Filter based on date less than or equal to parameter value. Dates are represented as strings formatted as YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagDateLt, "date-lt", "", "Filter based on date strictly less than parameter value. Dates are represented as strings formatted as YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagDateGe, "date-ge", "", "Filter based on date greater than or equal to parameter value. Dates are represented as strings formatted as YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagDateGt, "date-gt", "", "Filter based on date strictly greater than parameter value Dates are represented as strings formatted as YYYY-MM-DD.")
	cmd.Flags().StringVar(&flagLastModified, "last-modified", "", "Filter based on date of last modification.")
	cmd.Flags().StringVar(&flagLastModifiedLe, "last-modified-le", "", "Returns results that have been last modified before or on the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagLastModifiedLt, "last-modified-lt", "", "Returns results that have been last modified strictly before the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagLastModifiedGe, "last-modified-ge", "", "Returns results that have been last modified after or on the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagLastModifiedGt, "last-modified-gt", "", "Returns results that have been last modified strictly after the date provided as a parameter value.")
	cmd.Flags().StringVar(&flagSaleNumber, "sale-number", "", "Find all results with the sale number equal to the specified parameter.")
	cmd.Flags().BoolVar(&flagSettled, "settled", false, "When set to true, returns only sales that have been settled.")
	cmd.Flags().StringVar(&flagContactId, "contact-id", "", "Find all sale results for a given customer")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
