// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTimeUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "time-users",
		Short:       "Manage time users command groups",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTimeUsersGetCmd(flags))
	cmd.AddCommand(newTimeUsersGetCompaniesCmd(flags))
	return cmd
}
