// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTimeEntriesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "time-entries",
		Short:       "Get, create, update, and delete time entries",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTimeEntriesCreateInvoiceDraftFromCmd(flags))
	cmd.AddCommand(newTimeEntriesCreateTimeEntryCmd(flags))
	cmd.AddCommand(newTimeEntriesDeleteTimeEntryCmd(flags))
	cmd.AddCommand(newTimeEntriesGetCmd(flags))
	cmd.AddCommand(newTimeEntriesGetTimeEntryCmd(flags))
	cmd.AddCommand(newTimeEntriesUpdateTimeEntryCmd(flags))
	return cmd
}
