// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

// version is the printed CLI's version, overridable at build time via ldflags
// (.goreleaser.yaml injects -X fiken-cli/internal/cli.version).
//
// PATCH(release-2-0-0): 2.0.0 — the report envelope, period defaults and the
// guarded-write exit code are breaking changes; see CHANGELOG.md. A reprint
// resets this literal to the generator default.
var version = "2.0.0"

// newVersionCmd prints the CLI name and version. Shared by the HTTP and device
// generators so both printed-CLI shapes carry an identical version command.
func newVersionCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("%s %s\n", cmd.Root().Name(), version)
		},
	}
}
