// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

// version is the printed CLI's version, overridable at build time via ldflags
// (.goreleaser.yaml injects -X fiken-cli/internal/cli.version).
//
// PATCH(release-2-2-0): 2.2.0 — bumped in place at each release (2.0.0 was the
// breaking one: report envelope, period defaults, guarded-write exit code; 2.1.0
// fixed the page walk and added the result-count check; 2.2.0 adds document
// download and the per-pair incremental sync watermark); see CHANGELOG.md. A
// reprint resets this literal to the generator default.
var version = "2.2.0"

// newVersionCmd prints the CLI name and version. Shared by the HTTP and device
// generators so both printed-CLI shapes carry an identical version command.
func newVersionCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("%s %s\n", cmd.Root().Name(), version)
		},
	}
}
