#!/usr/bin/env bash
#
# check-boundaries.sh — HAND-AUTHORED. Enforces the two boundaries that
# `reports/printing-press-review.md` found were conventions rather than
# structure: the generated/hand-authored marker, and the patch-record ledger
# that is supposed to make a regeneration fail closed.
#
# Run via `make check`.
set -euo pipefail

cd "$(dirname "$0")/.."

ALLOW_FILE="scripts/check-boundaries.allow"
fail=0

# ---------------------------------------------------------------------------
# (a) Marker consistency: every .go file under internal/ and cmd/ carries
#     exactly one of the generator header (line 2) or HAND-AUTHORED (top 12
#     lines). Generated test stubs carry the generator header, so they pass.
# ---------------------------------------------------------------------------
violators=()
while IFS= read -r f; do
	gen=0
	hand=0
	if sed -n '2p' "$f" | grep -qF 'Generated by CLI Printing Press'; then gen=1; fi
	if head -12 "$f" | grep -qF 'HAND-AUTHORED'; then hand=1; fi
	if [ $((gen + hand)) -ne 1 ]; then
		violators+=("$f (generator header: $gen, HAND-AUTHORED: $hand)")
	fi
done < <(find internal cmd -name '*.go' -type f | sort)

if [ ${#violators[@]} -gt 0 ]; then
	echo "FAIL: marker consistency — each .go file needs exactly one of the generator header or HAND-AUTHORED:"
	printf '  %s\n' "${violators[@]}"
	fail=1
else
	echo "ok: marker consistency"
fi

# ---------------------------------------------------------------------------
# (b) No prefix matching on a vatType. Fiken vatTypes are a closed set; a
#     prefix match invents a private VAT table (root cause F1). Known
#     violations live in scripts/check-boundaries.allow as `path:pattern`
#     lines and are reported as warnings until they are fixed.
# ---------------------------------------------------------------------------
allow_hit() {
	local file="$1" text="$2" path pattern line
	[ -f "$ALLOW_FILE" ] || return 1
	while IFS= read -r line; do
		case "$line" in ''|'#'*) continue ;; esac
		path="${line%%:*}"
		pattern="${line#*:}"
		[ "$path" = "$file" ] || continue
		case "$text" in *"$pattern"*) return 0 ;; esac
	done < "$ALLOW_FILE"
	return 1
}

prefix_bad=()
prefix_warn=()
while IFS= read -r hit; do
	file="${hit%%:*}"
	file="${file#./}"
	rest="${hit#*:}"
	text="${rest#*:}"
	if allow_hit "$file" "$text"; then
		prefix_warn+=("$hit")
	else
		prefix_bad+=("$hit")
	fi
done < <(grep -rnE 'strings\.HasPrefix\(' --include='*.go' . | grep -iE 'vattype' || true)

for w in "${prefix_warn[@]:-}"; do
	[ -n "$w" ] && echo "warn: allowlisted vatType prefix match — $w"
done
if [ ${#prefix_bad[@]} -gt 0 ]; then
	echo "FAIL: strings.HasPrefix on a vatType (vatTypes are a closed set; use internal/fikencore):"
	printf '  %s\n' "${prefix_bad[@]}"
	fail=1
else
	echo "ok: no unlisted vatType prefix matching"
fi

# ---------------------------------------------------------------------------
# (c) Every patch record parses, declares files[], and every call_sites[]
#     needle is still present in one of those files. This is what makes a
#     regeneration fail closed instead of silently dropping a fix.
# ---------------------------------------------------------------------------
if ! python3 - <<'PY'; then
import glob
import json
import sys

bad = []
for path in sorted(glob.glob(".printing-press-patches/*.json")):
    try:
        rec = json.load(open(path))
    except Exception as exc:  # malformed JSON is a failure, not a skip
        bad.append("%s: does not parse: %s" % (path, exc))
        continue
    files = rec.get("files")
    if not isinstance(files, list) or not files:
        bad.append("%s: missing or empty files[]" % path)
        continue
    for f in files:
        try:
            open(f).read()
        except OSError as exc:
            bad.append("%s: files[] entry unreadable: %s" % (path, exc))
    bodies = []
    for f in files:
        try:
            bodies.append(open(f, encoding="utf-8", errors="replace").read())
        except OSError:
            pass
    for needle in rec.get("call_sites", []) or []:
        if not any(needle in b for b in bodies):
            bad.append("%s: call site not found in files[]: %r" % (path, needle))

if bad:
    print("FAIL: patch records:")
    for b in bad:
        print("  " + b)
    sys.exit(1)
print("ok: patch records (%d)" % len(glob.glob(".printing-press-patches/*.json")))
PY
	fail=1
fi

# ---------------------------------------------------------------------------
# (d) No .md-only patch record: every .md in .printing-press-patches/ needs a
#     sibling .json, because the validator only reads *.json.
# ---------------------------------------------------------------------------
orphans=()
for md in .printing-press-patches/*.md; do
	[ -e "$md" ] || continue
	[ -e "${md%.md}.json" ] || orphans+=("$md")
done
if [ ${#orphans[@]} -gt 0 ]; then
	echo "FAIL: patch note with no machine-readable sibling .json (the validator only reads *.json):"
	printf '  %s\n' "${orphans[@]}"
	fail=1
else
	echo "ok: no .md-only patch records"
fi

# ---------------------------------------------------------------------------
# (e) Doc claims. The docs and the MCP feature index advertised two
#     capabilities the code does not have: a drift debit≠credit imbalance
#     check (the mirror's journal lines carry a signed amount but no
#     debit/credit direction, so it is not computable) and a
#     `rollup --by project` dimension (the mirrored lines carry no project).
#     Both are one copy-paste of an old blurb away from coming back.
#     Negated mentions ("... is not checked") and `validate`'s legitimate
#     "balanced debit/credit" wording are excluded on purpose.
# ---------------------------------------------------------------------------
DOC_FILES=(.printing-press.json skills/fiken/SKILL.md README.md docs/features.md docs/design.md docs/commands.md internal/mcp/tools.go)
doc_bad=()
while IFS= read -r hit; do
	[ -n "$hit" ] && doc_bad+=("$hit")
done < <(grep -niE 'debit≠credit|debit/credit imbalance|by project|project, or contact|clearing-account' "${DOC_FILES[@]}" |
	grep -viE 'is not checked|not computable|balanced debit/credit|roadmap|posts no clearing-account|not composed|posted by hand' |
	cut -c1-140 || true)

if [ ${#doc_bad[@]} -gt 0 ]; then
	echo "FAIL: doc claims — drift does not check debit≠credit imbalance, rollup has no project dimension, and reconcile posts no clearing-account entries:"
	printf '  %s\n' "${doc_bad[@]}"
	fail=1
else
	echo "ok: doc claims"
fi

if [ "$fail" -ne 0 ]; then
	echo "check-boundaries: FAILED"
	exit 1
fi
echo "check-boundaries: OK"
