#!/usr/bin/env bash
#
# harmonize.sh — re-apply the fiken-cli frontend naming on a freshly generated
# Printing Press tree, so `printing-press generate` / `regen-merge` keep working
# (the "regen prize") while the shipped command stays `fiken-cli`.
#
# PP always emits `fiken-pp-cli` / `fiken-pp-mcp`. Run this on the freshly
# generated tree BEFORE `regen-merge` so both sides are `fiken-cli` and the
# merge sees only real drift:
#
#     printing-press generate --spec spec.yaml --name fiken --output /tmp/fresh
#     scripts/harmonize.sh /tmp/fresh
#     printing-press regen-merge --published . --fresh /tmp/fresh   # (or your merge step)
#
# Backend stays PP: this intentionally does NOT touch the
# "// Generated by CLI Printing Press ... DO NOT EDIT." headers or the
# pp:data-source / pp:typed-exit-codes annotations — regen-merge classification
# and dogfood depend on them. It only harmonizes the user-facing *name*.
#
# Note: README/SKILL install boilerplate (the public-library install sections,
# MCPB download links) is hand-maintained frontend, not covered here — re-run a
# docs pass after regen if PP reinjects those anchors. Only the SKILL H1 title
# is normalized below (deterministic, safe).
set -euo pipefail
ROOT="${1:-.}"
cd "$ROOT"

# 1. Command directories.
[ -d cmd/fiken-pp-cli ] && { git mv cmd/fiken-pp-cli cmd/fiken-cli 2>/dev/null || mv cmd/fiken-pp-cli cmd/fiken-cli; }
[ -d cmd/fiken-pp-mcp ] && { git mv cmd/fiken-pp-mcp cmd/fiken-mcp 2>/dev/null || mv cmd/fiken-pp-mcp cmd/fiken-mcp; }

# 2. Content: module path, imports, binary names, and bare slugs — everywhere
#    except the .git dir. (fiken-pp-cli -> fiken-cli, fiken-pp-mcp -> fiken-mcp.)
grep -rIl --exclude-dir=.git -e 'fiken-pp-cli' -e 'fiken-pp-mcp' . 2>/dev/null | while read -r f; do
  perl -pi -e 's/fiken-pp-cli/fiken-cli/g; s/fiken-pp-mcp/fiken-mcp/g;' "$f"
done

# 3. SKILL.md H1 title, if PP reinjected the "— Printing Press CLI" suffix.
[ -f skills/fiken/SKILL.md ] && perl -pi -e 's/^# Fiken — Printing Press CLI\s*$/# Fiken CLI\n/' skills/fiken/SKILL.md || true

echo "harmonized -> fiken-cli. Now: go build ./... && go test ./..."
