// Copyright 2026 Lasse Jellum and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	mcptools "fiken-cli/internal/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// Transport selection order: --transport flag, then FIKEN_MCP_TRANSPORT env (legacy PP_MCP_TRANSPORT still honored),
// then the first transport declared in the spec (see MCPConfig.Transport).
// The flag surface lets one binary serve stdio locally and streamable HTTP
// when hosted in a container or remote sandbox, matching the Anthropic
// guidance that production agents need a remote option.

const (
	defaultHTTPAddr = ":7777"
)

// version is the printed MCP server's version, overridable at build time via ldflags.
var version = "0.0.0-dev"

func main() {
	s := server.NewMCPServer(
		"Fiken",
		version,
		server.WithToolCapabilities(false),
	)

	mcptools.RegisterTools(s)

	transport := flag.String("transport", defaultTransport(), "MCP transport: stdio | http")
	addr := flag.String("addr", defaultHTTPAddr, "bind address for http transport (host:port or :port)")
	requireAuth := flag.Bool("require-auth", defaultRequireAuth(), "http: require a Fiken OAuth2 Bearer token per request (401 + OAuth discovery when missing)")
	flag.Parse()

	switch strings.ToLower(*transport) {
	case "stdio":
		if err := server.ServeStdio(s); err != nil {
			fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
			os.Exit(1)
		}
	case "http":
		// Fiken OAuth2 is the authorization layer: each request's Bearer token
		// is forwarded to the Fiken API, and Fiken is advertised as the OAuth
		// authorization server for discovery. See internal/mcp/fiken_http_auth.go.
		if err := mcptools.ServeStreamableHTTPWithFikenOAuth(s, *addr, *requireAuth); err != nil {
			fmt.Fprintf(os.Stderr, "MCP server error: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Fprintf(os.Stderr, "unknown --transport %q (supported: stdio, http)\n", *transport)
		os.Exit(2)
	}
}

// defaultTransport reads FIKEN_MCP_TRANSPORT (falling back to the legacy
// PP_MCP_TRANSPORT so a freshly-regenerated binary still honors the old name),
// otherwise falls back to "stdio" so running the binary with no args keeps
// today's behavior. Container-hosted agents can pin the transport via env
// without a flag, which matches how hosted-agent supervisors pass config.
func defaultTransport() string {
	if t := os.Getenv("FIKEN_MCP_TRANSPORT"); t != "" {
		return t
	}
	if t := os.Getenv("PP_MCP_TRANSPORT"); t != "" {
		return t
	}
	return "stdio"
}

// defaultRequireAuth lets a deployment force per-request Fiken OAuth on the HTTP
// transport via FIKEN_MCP_REQUIRE_AUTH=1 without passing a flag. Default off, so
// a single-user server falls back to its locally-configured token.
func defaultRequireAuth() bool {
	v := strings.ToLower(os.Getenv("FIKEN_MCP_REQUIRE_AUTH"))
	return v == "1" || v == "true" || v == "yes"
}
